// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: AddItemToPlaylistBody
export const AddItemToPlaylistBody = z.object({
  // Name: AddItemToPlaylistBody.trackId
  "trackId": z.string(),
});
export type AddItemToPlaylistBody = z.infer<typeof AddItemToPlaylistBody>;

// Name: AddPlaylistFilter
export const AddPlaylistFilter = z.object({
  // Name: AddPlaylistFilter.filterId
  "filterId": z.string(),
});
export type AddPlaylistFilter = z.infer<typeof AddPlaylistFilter>;

// Name: AddPlaylistFilterBody
export const AddPlaylistFilterBody = z.object({
  // Name: AddPlaylistFilterBody.name
  "name": z.string(),
  // Name: AddPlaylistFilterBody.filter
  "filter": z.string(),
});
export type AddPlaylistFilterBody = z.infer<typeof AddPlaylistFilterBody>;

// Name: AddTrackEventBody
export const AddTrackEventBody = z.object({
  // Name: AddTrackEventBody.position
  "position": z.number(),
  // Name: AddTrackEventBody.source
  "source": z.string(),
});
export type AddTrackEventBody = z.infer<typeof AddTrackEventBody>;

// Name: Images
export const Images = z.object({
  // Name: Images.original
  "original": z.string(),
  // Name: Images.small
  "small": z.string(),
  // Name: Images.medium
  "medium": z.string(),
  // Name: Images.large
  "large": z.string(),
});
export type Images = z.infer<typeof Images>;

// Name: ArtistInfo
export const ArtistInfo = z.object({
  // Name: ArtistInfo.id
  "id": z.string(),
  // Name: ArtistInfo.name
  "name": z.string(),
});
export type ArtistInfo = z.infer<typeof ArtistInfo>;

// Name: Album
export const Album = z.object({
  // Name: Album.id
  "id": z.string(),
  // Name: Album.name
  "name": z.string(),
  // Name: Album.year
  "year": z.number().nullable(),
  // Name: Album.coverArt
  "coverArt": Images,
  // Name: Album.artists
  "artists": z.array(ArtistInfo),
  // Name: Album.tags
  "tags": z.array(z.string()),
  // Name: Album.created
  "created": z.string(),
  // Name: Album.updated
  "updated": z.string(),
});
export type Album = z.infer<typeof Album>;

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
  // Name: ApiToken.created
  "created": z.string(),
  // Name: ApiToken.updated
  "updated": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: Artist
export const Artist = z.object({
  // Name: Artist.id
  "id": z.string(),
  // Name: Artist.name
  "name": z.string(),
  // Name: Artist.coverArt
  "coverArt": Images,
  // Name: Artist.tags
  "tags": z.array(z.string()),
  // Name: Artist.created
  "created": z.string(),
  // Name: Artist.updated
  "updated": z.string(),
});
export type Artist = z.infer<typeof Artist>;

// Name: AuthClaimQuickConnectCodeBody
export const AuthClaimQuickConnectCodeBody = z.object({
  // Name: AuthClaimQuickConnectCodeBody.code
  "code": z.string(),
});
export type AuthClaimQuickConnectCodeBody = z.infer<typeof AuthClaimQuickConnectCodeBody>;

// Name: AuthFinishProvider
export const AuthFinishProvider = z.object({
  // Name: AuthFinishProvider.token
  "token": z.string(),
});
export type AuthFinishProvider = z.infer<typeof AuthFinishProvider>;

// Name: AuthFinishProviderBody
export const AuthFinishProviderBody = z.object({
  // Name: AuthFinishProviderBody.requestId
  "requestId": z.string(),
  // Name: AuthFinishProviderBody.challenge
  "challenge": z.string(),
});
export type AuthFinishProviderBody = z.infer<typeof AuthFinishProviderBody>;

// Name: AuthFinishQuickConnect
export const AuthFinishQuickConnect = z.object({
  // Name: AuthFinishQuickConnect.token
  "token": z.string(),
});
export type AuthFinishQuickConnect = z.infer<typeof AuthFinishQuickConnect>;

// Name: AuthFinishQuickConnectBody
export const AuthFinishQuickConnectBody = z.object({
  // Name: AuthFinishQuickConnectBody.code
  "code": z.string(),
  // Name: AuthFinishQuickConnectBody.challenge
  "challenge": z.string(),
});
export type AuthFinishQuickConnectBody = z.infer<typeof AuthFinishQuickConnectBody>;

// Name: AuthGetProviderStatus
export const AuthGetProviderStatus = z.object({
  // Name: AuthGetProviderStatus.status
  "status": z.string(),
});
export type AuthGetProviderStatus = z.infer<typeof AuthGetProviderStatus>;

// Name: AuthGetProviderStatusBody
export const AuthGetProviderStatusBody = z.object({
  // Name: AuthGetProviderStatusBody.requestId
  "requestId": z.string(),
  // Name: AuthGetProviderStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetProviderStatusBody = z.infer<typeof AuthGetProviderStatusBody>;

// Name: AuthGetQuickConnectStatus
export const AuthGetQuickConnectStatus = z.object({
  // Name: AuthGetQuickConnectStatus.status
  "status": z.string(),
});
export type AuthGetQuickConnectStatus = z.infer<typeof AuthGetQuickConnectStatus>;

// Name: AuthGetQuickConnectStatusBody
export const AuthGetQuickConnectStatusBody = z.object({
  // Name: AuthGetQuickConnectStatusBody.code
  "code": z.string(),
  // Name: AuthGetQuickConnectStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetQuickConnectStatusBody = z.infer<typeof AuthGetQuickConnectStatusBody>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.requestId
  "requestId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.challenge
  "challenge": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthInitiateBody
export const AuthInitiateBody = z.object({
  // Name: AuthInitiateBody.providerId
  "providerId": z.string(),
});
export type AuthInitiateBody = z.infer<typeof AuthInitiateBody>;

// Name: AuthProvider
export const AuthProvider = z.object({
  // Name: AuthProvider.id
  "id": z.string(),
  // Name: AuthProvider.displayName
  "displayName": z.string(),
});
export type AuthProvider = z.infer<typeof AuthProvider>;

// Name: AuthQuickConnectInitiate
export const AuthQuickConnectInitiate = z.object({
  // Name: AuthQuickConnectInitiate.code
  "code": z.string(),
  // Name: AuthQuickConnectInitiate.challenge
  "challenge": z.string(),
  // Name: AuthQuickConnectInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthQuickConnectInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthQuickConnectInitiate = z.infer<typeof AuthQuickConnectInitiate>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: CreatePlaylist
export const CreatePlaylist = z.object({
  // Name: CreatePlaylist.id
  "id": z.string(),
});
export type CreatePlaylist = z.infer<typeof CreatePlaylist>;

// Name: CreatePlaylistBody
export const CreatePlaylistBody = z.object({
  // Name: CreatePlaylistBody.name
  "name": z.string(),
});
export type CreatePlaylistBody = z.infer<typeof CreatePlaylistBody>;

// Name: CreateTrackFilterBody
export const CreateTrackFilterBody = z.object({
  // Name: CreateTrackFilterBody.name
  "name": z.string(),
  // Name: CreateTrackFilterBody.filter
  "filter": z.string(),
});
export type CreateTrackFilterBody = z.infer<typeof CreateTrackFilterBody>;

// Name: EditPlaylistBody
export const EditPlaylistBody = z.object({
  // Name: EditPlaylistBody.name
  "name": z.string().nullable().optional(),
  // Name: EditPlaylistBody.coverUrl
  "coverUrl": z.string().nullable().optional(),
});
export type EditPlaylistBody = z.infer<typeof EditPlaylistBody>;

// Name: EditPlaylistFilterBody
export const EditPlaylistFilterBody = z.object({
  // Name: EditPlaylistFilterBody.name
  "name": z.string().nullable().optional(),
  // Name: EditPlaylistFilterBody.filter
  "filter": z.string().nullable().optional(),
});
export type EditPlaylistFilterBody = z.infer<typeof EditPlaylistFilterBody>;

// Name: GetAlbumById
export const GetAlbumById = z.object({
  // Name: GetAlbumById.album
  "album": Album,
});
export type GetAlbumById = z.infer<typeof GetAlbumById>;

// Name: Track
export const Track = z.object({
  // Name: Track.id
  "id": z.string(),
  // Name: Track.name
  "name": z.string(),
  // Name: Track.order
  "order": z.number().nullable(),
  // Name: Track.duration
  "duration": z.number(),
  // Name: Track.number
  "number": z.number().nullable(),
  // Name: Track.year
  "year": z.number().nullable(),
  // Name: Track.coverArt
  "coverArt": Images,
  // Name: Track.albumId
  "albumId": z.string(),
  // Name: Track.albumName
  "albumName": z.string(),
  // Name: Track.artists
  "artists": z.array(ArtistInfo),
  // Name: Track.tags
  "tags": z.array(z.string()),
  // Name: Track.created
  "created": z.string(),
  // Name: Track.updated
  "updated": z.string(),
});
export type Track = z.infer<typeof Track>;

// Name: GetAlbumTracks
export const GetAlbumTracks = z.object({
  // Name: GetAlbumTracks.tracks
  "tracks": z.array(Track),
});
export type GetAlbumTracks = z.infer<typeof GetAlbumTracks>;

// Name: Page
export const Page = z.object({
  // Name: Page.page
  "page": z.number(),
  // Name: Page.perPage
  "perPage": z.number(),
  // Name: Page.totalItems
  "totalItems": z.number(),
  // Name: Page.totalPages
  "totalPages": z.number(),
});
export type Page = z.infer<typeof Page>;

// Name: GetAlbums
export const GetAlbums = z.object({
  // Name: GetAlbums.page
  "page": Page,
  // Name: GetAlbums.albums
  "albums": z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

// Name: GetApiTokens
export const GetApiTokens = z.object({
  // Name: GetApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetApiTokens = z.infer<typeof GetApiTokens>;

// Name: GetArtistAlbumsById
export const GetArtistAlbumsById = z.object({
  // Name: GetArtistAlbumsById.albums
  "albums": z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

// Name: GetArtistById
export const GetArtistById = z.object({
  // Name: GetArtistById.artist
  "artist": Artist,
});
export type GetArtistById = z.infer<typeof GetArtistById>;

// Name: GetArtists
export const GetArtists = z.object({
  // Name: GetArtists.page
  "page": Page,
  // Name: GetArtists.artists
  "artists": z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

// Name: GetAuthProviders
export const GetAuthProviders = z.object({
  // Name: GetAuthProviders.providers
  "providers": z.array(AuthProvider),
});
export type GetAuthProviders = z.infer<typeof GetAuthProviders>;

// Name: GetFavoriteTrackIds
export const GetFavoriteTrackIds = z.object({
  // Name: GetFavoriteTrackIds.ids
  "ids": z.array(z.string()),
});
export type GetFavoriteTrackIds = z.infer<typeof GetFavoriteTrackIds>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.email
  "email": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.picture
  "picture": Images,
  // Name: GetMe.quickPlaylist
  "quickPlaylist": z.string().nullable(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: MediaRef
export const MediaRef = z.object({
  // Name: MediaRef.id
  "id": z.string(),
  // Name: MediaRef.name
  "name": z.string(),
});
export type MediaRef = z.infer<typeof MediaRef>;

// Name: MediaItem
export const MediaItem = z.object({
  // Name: MediaItem.trackId
  "trackId": z.string(),
  // Name: MediaItem.name
  "name": z.string(),
  // Name: MediaItem.artists
  "artists": z.array(MediaRef),
  // Name: MediaItem.album
  "album": MediaRef,
  // Name: MediaItem.coverArt
  "coverArt": Images,
});
export type MediaItem = z.infer<typeof MediaItem>;

// Name: GetMedia
export const GetMedia = z.object({
  // Name: GetMedia.items
  "items": z.array(MediaItem),
});
export type GetMedia = z.infer<typeof GetMedia>;

// Name: GetMediaCommonBody
export const GetMediaCommonBody = z.object({
  // Name: GetMediaCommonBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaCommonBody.offset
  "offset": z.number().optional(),
});
export type GetMediaCommonBody = z.infer<typeof GetMediaCommonBody>;

// Name: GetMediaFromAlbumBody
export const GetMediaFromAlbumBody = z.object({
  // Name: GetMediaFromAlbumBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromAlbumBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromAlbumBody = z.infer<typeof GetMediaFromAlbumBody>;

// Name: GetMediaFromArtistBody
export const GetMediaFromArtistBody = z.object({
  // Name: GetMediaFromArtistBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromArtistBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromArtistBody = z.infer<typeof GetMediaFromArtistBody>;

// Name: GetMediaFromFilterBody
export const GetMediaFromFilterBody = z.object({
  // Name: GetMediaFromFilterBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromFilterBody.offset
  "offset": z.number().optional(),
  // Name: GetMediaFromFilterBody.filter
  "filter": z.string(),
});
export type GetMediaFromFilterBody = z.infer<typeof GetMediaFromFilterBody>;

// Name: GetMediaFromIdsBody
export const GetMediaFromIdsBody = z.object({
  // Name: GetMediaFromIdsBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromIdsBody.offset
  "offset": z.number().optional(),
  // Name: GetMediaFromIdsBody.trackIds
  "trackIds": z.array(z.string()),
  // Name: GetMediaFromIdsBody.keepOrder
  "keepOrder": z.boolean().optional(),
});
export type GetMediaFromIdsBody = z.infer<typeof GetMediaFromIdsBody>;

// Name: MediaFormat
export const MediaFormat = z.object({
  // Name: MediaFormat.name
  "name": z.string(),
  // Name: MediaFormat.format
  "format": z.string(),
  // Name: MediaFormat.ext
  "ext": z.string(),
  // Name: MediaFormat.qualityHighBitrate
  "qualityHighBitrate": z.number(),
  // Name: MediaFormat.qualityMediumBitrate
  "qualityMediumBitrate": z.number(),
  // Name: MediaFormat.qualityLowBitrate
  "qualityLowBitrate": z.number(),
  // Name: MediaFormat.order
  "order": z.number(),
});
export type MediaFormat = z.infer<typeof MediaFormat>;

// Name: MediaDeviceSpec
export const MediaDeviceSpec = z.object({
  // Name: MediaDeviceSpec.name
  "name": z.string(),
  // Name: MediaDeviceSpec.preferedFormat
  "preferedFormat": z.string(),
  // Name: MediaDeviceSpec.allowedFormats
  "allowedFormats": z.array(z.string()),
});
export type MediaDeviceSpec = z.infer<typeof MediaDeviceSpec>;

// Name: GetMediaSettings
export const GetMediaSettings = z.object({
  // Name: GetMediaSettings.formats
  "formats": z.array(MediaFormat),
  // Name: GetMediaSettings.deviceSpecs
  "deviceSpecs": z.array(MediaDeviceSpec),
});
export type GetMediaSettings = z.infer<typeof GetMediaSettings>;

// Name: GetPlaylistById
export const GetPlaylistById = z.object({
  // Name: GetPlaylistById.id
  "id": z.string(),
  // Name: GetPlaylistById.name
  "name": z.string(),
  // Name: GetPlaylistById.coverArt
  "coverArt": Images,
  // Name: GetPlaylistById.ownerId
  "ownerId": z.string(),
  // Name: GetPlaylistById.ownerDisplayName
  "ownerDisplayName": z.string(),
  // Name: GetPlaylistById.ownerPicture
  "ownerPicture": Images,
  // Name: GetPlaylistById.trackCount
  "trackCount": z.number(),
  // Name: GetPlaylistById.created
  "created": z.string(),
  // Name: GetPlaylistById.updated
  "updated": z.string(),
});
export type GetPlaylistById = z.infer<typeof GetPlaylistById>;

// Name: PlaylistFilter
export const PlaylistFilter = z.object({
  // Name: PlaylistFilter.filterId
  "filterId": z.string(),
  // Name: PlaylistFilter.playlistId
  "playlistId": z.string(),
  // Name: PlaylistFilter.name
  "name": z.string(),
  // Name: PlaylistFilter.filter
  "filter": z.string(),
  // Name: PlaylistFilter.created
  "created": z.string(),
  // Name: PlaylistFilter.updated
  "updated": z.string(),
});
export type PlaylistFilter = z.infer<typeof PlaylistFilter>;

// Name: GetPlaylistFilters
export const GetPlaylistFilters = z.object({
  // Name: GetPlaylistFilters.filters
  "filters": z.array(PlaylistFilter),
});
export type GetPlaylistFilters = z.infer<typeof GetPlaylistFilters>;

// Name: GetPlaylistItems
export const GetPlaylistItems = z.object({
  // Name: GetPlaylistItems.page
  "page": Page,
  // Name: GetPlaylistItems.items
  "items": z.array(Track),
});
export type GetPlaylistItems = z.infer<typeof GetPlaylistItems>;

// Name: Playlist
export const Playlist = z.object({
  // Name: Playlist.id
  "id": z.string(),
  // Name: Playlist.name
  "name": z.string(),
  // Name: Playlist.coverArt
  "coverArt": Images,
  // Name: Playlist.ownerId
  "ownerId": z.string(),
  // Name: Playlist.ownerDisplayName
  "ownerDisplayName": z.string(),
  // Name: Playlist.ownerPicture
  "ownerPicture": Images,
  // Name: Playlist.trackCount
  "trackCount": z.number(),
  // Name: Playlist.created
  "created": z.string(),
  // Name: Playlist.updated
  "updated": z.string(),
});
export type Playlist = z.infer<typeof Playlist>;

// Name: GetPlaylists
export const GetPlaylists = z.object({
  // Name: GetPlaylists.page
  "page": Page,
  // Name: GetPlaylists.playlists
  "playlists": z.array(Playlist),
});
export type GetPlaylists = z.infer<typeof GetPlaylists>;

// Name: GetQuickPlaylistIds
export const GetQuickPlaylistIds = z.object({
  // Name: GetQuickPlaylistIds.ids
  "ids": z.array(z.string()),
});
export type GetQuickPlaylistIds = z.infer<typeof GetQuickPlaylistIds>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: GetTrackById
export const GetTrackById = z.object({
  // Name: GetTrackById.track
  "track": Track,
});
export type GetTrackById = z.infer<typeof GetTrackById>;

// Name: TrackFilter
export const TrackFilter = z.object({
  // Name: TrackFilter.filterId
  "filterId": z.string(),
  // Name: TrackFilter.userId
  "userId": z.string(),
  // Name: TrackFilter.name
  "name": z.string(),
  // Name: TrackFilter.filter
  "filter": z.string(),
  // Name: TrackFilter.created
  "created": z.string(),
  // Name: TrackFilter.updated
  "updated": z.string(),
});
export type TrackFilter = z.infer<typeof TrackFilter>;

// Name: GetTrackFilters
export const GetTrackFilters = z.object({
  // Name: GetTrackFilters.filters
  "filters": z.array(TrackFilter),
});
export type GetTrackFilters = z.infer<typeof GetTrackFilters>;

// Name: GetTracks
export const GetTracks = z.object({
  // Name: GetTracks.page
  "page": Page,
  // Name: GetTracks.tracks
  "tracks": z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

// Name: UserData
export const UserData = z.object({
  // Name: UserData.id
  "id": z.string(),
  // Name: UserData.displayName
  "displayName": z.string(),
  // Name: UserData.role
  "role": z.string(),
  // Name: UserData.picture
  "picture": Images,
  // Name: UserData.created
  "created": z.string(),
});
export type UserData = z.infer<typeof UserData>;

// Name: GetUser
export const GetUser = z.object({
  // Name: GetUser.user
  "user": UserData,
});
export type GetUser = z.infer<typeof GetUser>;

// Name: GetUserFavorites
export const GetUserFavorites = z.object({
  // Name: GetUserFavorites.page
  "page": Page,
  // Name: GetUserFavorites.items
  "items": z.array(Track),
});
export type GetUserFavorites = z.infer<typeof GetUserFavorites>;

// Name: RemovePlaylistItemBody
export const RemovePlaylistItemBody = z.object({
  // Name: RemovePlaylistItemBody.trackId
  "trackId": z.string(),
});
export type RemovePlaylistItemBody = z.infer<typeof RemovePlaylistItemBody>;

// Name: ReorderPlaylistItemsBody
export const ReorderPlaylistItemsBody = z.object({
  // Name: ReorderPlaylistItemsBody.before
  "before": z.boolean(),
  // Name: ReorderPlaylistItemsBody.anchorTrackId
  "anchorTrackId": z.string(),
  // Name: ReorderPlaylistItemsBody.trackIds
  "trackIds": z.array(z.string()),
});
export type ReorderPlaylistItemsBody = z.infer<typeof ReorderPlaylistItemsBody>;

// Name: SearchAlbums
export const SearchAlbums = z.object({
  // Name: SearchAlbums.albums
  "albums": z.array(Album),
});
export type SearchAlbums = z.infer<typeof SearchAlbums>;

// Name: SearchArtists
export const SearchArtists = z.object({
  // Name: SearchArtists.artists
  "artists": z.array(Artist),
});
export type SearchArtists = z.infer<typeof SearchArtists>;

// Name: SearchPlaylists
export const SearchPlaylists = z.object({
  // Name: SearchPlaylists.playlists
  "playlists": z.array(Playlist),
});
export type SearchPlaylists = z.infer<typeof SearchPlaylists>;

// Name: SearchTracks
export const SearchTracks = z.object({
  // Name: SearchTracks.tracks
  "tracks": z.array(Track),
});
export type SearchTracks = z.infer<typeof SearchTracks>;

// Name: SearchUsers
export const SearchUsers = z.object({
  // Name: SearchUsers.users
  "users": z.array(UserData),
});
export type SearchUsers = z.infer<typeof SearchUsers>;

// Name: SetQuickPlaylistBody
export const SetQuickPlaylistBody = z.object({
  // Name: SetQuickPlaylistBody.playlistId
  "playlistId": z.string(),
});
export type SetQuickPlaylistBody = z.infer<typeof SetQuickPlaylistBody>;

// Name: UpdateMeBody
export const UpdateMeBody = z.object({
  // Name: UpdateMeBody.displayName
  "displayName": z.string().nullable().optional(),
});
export type UpdateMeBody = z.infer<typeof UpdateMeBody>;

// Name: UpdateTrackFilterBody
export const UpdateTrackFilterBody = z.object({
  // Name: UpdateTrackFilterBody.name
  "name": z.string().nullable().optional(),
  // Name: UpdateTrackFilterBody.filter
  "filter": z.string().nullable().optional(),
});
export type UpdateTrackFilterBody = z.infer<typeof UpdateTrackFilterBody>;

