// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: AddItemToPlaylistBody
export const AddItemToPlaylistBody = z.object({
  // Name: AddItemToPlaylistBody.trackId
  "trackId": z.string(),
});
export type AddItemToPlaylistBody = z.infer<typeof AddItemToPlaylistBody>;

// Name: Images
export const Images = z.object({
  // Name: Images.original
  "original": z.string(),
  // Name: Images.small
  "small": z.string(),
  // Name: Images.medium
  "medium": z.string(),
  // Name: Images.large
  "large": z.string(),
});
export type Images = z.infer<typeof Images>;

// Name: ArtistInfo
export const ArtistInfo = z.object({
  // Name: ArtistInfo.id
  "id": z.string(),
  // Name: ArtistInfo.name
  "name": z.string(),
});
export type ArtistInfo = z.infer<typeof ArtistInfo>;

// Name: Album
export const Album = z.object({
  // Name: Album.id
  "id": z.string(),
  // Name: Album.name
  "name": z.string(),
  // Name: Album.year
  "year": z.number().nullable(),
  // Name: Album.coverArt
  "coverArt": Images,
  // Name: Album.artists
  "artists": z.array(ArtistInfo),
  // Name: Album.tags
  "tags": z.array(z.string()),
  // Name: Album.created
  "created": z.number(),
  // Name: Album.updated
  "updated": z.number(),
});
export type Album = z.infer<typeof Album>;

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: Artist
export const Artist = z.object({
  // Name: Artist.id
  "id": z.string(),
  // Name: Artist.name
  "name": z.string(),
  // Name: Artist.picture
  "picture": Images,
  // Name: Artist.tags
  "tags": z.array(z.string()),
  // Name: Artist.created
  "created": z.number(),
  // Name: Artist.updated
  "updated": z.number(),
});
export type Artist = z.infer<typeof Artist>;

// Name: AuthClaimQuickConnectCodeBody
export const AuthClaimQuickConnectCodeBody = z.object({
  // Name: AuthClaimQuickConnectCodeBody.code
  "code": z.string(),
});
export type AuthClaimQuickConnectCodeBody = z.infer<typeof AuthClaimQuickConnectCodeBody>;

// Name: AuthFinishProvider
export const AuthFinishProvider = z.object({
  // Name: AuthFinishProvider.token
  "token": z.string(),
});
export type AuthFinishProvider = z.infer<typeof AuthFinishProvider>;

// Name: AuthFinishProviderBody
export const AuthFinishProviderBody = z.object({
  // Name: AuthFinishProviderBody.requestId
  "requestId": z.string(),
  // Name: AuthFinishProviderBody.challenge
  "challenge": z.string(),
});
export type AuthFinishProviderBody = z.infer<typeof AuthFinishProviderBody>;

// Name: AuthFinishQuickConnect
export const AuthFinishQuickConnect = z.object({
  // Name: AuthFinishQuickConnect.token
  "token": z.string(),
});
export type AuthFinishQuickConnect = z.infer<typeof AuthFinishQuickConnect>;

// Name: AuthFinishQuickConnectBody
export const AuthFinishQuickConnectBody = z.object({
  // Name: AuthFinishQuickConnectBody.code
  "code": z.string(),
  // Name: AuthFinishQuickConnectBody.challenge
  "challenge": z.string(),
});
export type AuthFinishQuickConnectBody = z.infer<typeof AuthFinishQuickConnectBody>;

// Name: AuthGetProviderStatus
export const AuthGetProviderStatus = z.object({
  // Name: AuthGetProviderStatus.status
  "status": z.string(),
});
export type AuthGetProviderStatus = z.infer<typeof AuthGetProviderStatus>;

// Name: AuthGetProviderStatusBody
export const AuthGetProviderStatusBody = z.object({
  // Name: AuthGetProviderStatusBody.requestId
  "requestId": z.string(),
  // Name: AuthGetProviderStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetProviderStatusBody = z.infer<typeof AuthGetProviderStatusBody>;

// Name: AuthGetQuickConnectStatus
export const AuthGetQuickConnectStatus = z.object({
  // Name: AuthGetQuickConnectStatus.status
  "status": z.string(),
});
export type AuthGetQuickConnectStatus = z.infer<typeof AuthGetQuickConnectStatus>;

// Name: AuthGetQuickConnectStatusBody
export const AuthGetQuickConnectStatusBody = z.object({
  // Name: AuthGetQuickConnectStatusBody.code
  "code": z.string(),
  // Name: AuthGetQuickConnectStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetQuickConnectStatusBody = z.infer<typeof AuthGetQuickConnectStatusBody>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.requestId
  "requestId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.challenge
  "challenge": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthInitiateBody
export const AuthInitiateBody = z.object({
  // Name: AuthInitiateBody.providerId
  "providerId": z.string(),
});
export type AuthInitiateBody = z.infer<typeof AuthInitiateBody>;

// Name: AuthProvider
export const AuthProvider = z.object({
  // Name: AuthProvider.id
  "id": z.string(),
  // Name: AuthProvider.displayName
  "displayName": z.string(),
});
export type AuthProvider = z.infer<typeof AuthProvider>;

// Name: AuthQuickConnectInitiate
export const AuthQuickConnectInitiate = z.object({
  // Name: AuthQuickConnectInitiate.code
  "code": z.string(),
  // Name: AuthQuickConnectInitiate.challenge
  "challenge": z.string(),
  // Name: AuthQuickConnectInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthQuickConnectInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthQuickConnectInitiate = z.infer<typeof AuthQuickConnectInitiate>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: CreatePlaylist
export const CreatePlaylist = z.object({
  // Name: CreatePlaylist.id
  "id": z.string(),
});
export type CreatePlaylist = z.infer<typeof CreatePlaylist>;

// Name: CreatePlaylistBody
export const CreatePlaylistBody = z.object({
  // Name: CreatePlaylistBody.name
  "name": z.string(),
});
export type CreatePlaylistBody = z.infer<typeof CreatePlaylistBody>;

// Name: CreateTaglist
export const CreateTaglist = z.object({
  // Name: CreateTaglist.id
  "id": z.string(),
});
export type CreateTaglist = z.infer<typeof CreateTaglist>;

// Name: CreateTaglistBody
export const CreateTaglistBody = z.object({
  // Name: CreateTaglistBody.name
  "name": z.string(),
  // Name: CreateTaglistBody.filter
  "filter": z.string(),
});
export type CreateTaglistBody = z.infer<typeof CreateTaglistBody>;

// Name: GetAlbumById
export const GetAlbumById = z.object({
  // Name: GetAlbumById.id
  "id": z.string(),
  // Name: GetAlbumById.name
  "name": z.string(),
  // Name: GetAlbumById.year
  "year": z.number().nullable(),
  // Name: GetAlbumById.coverArt
  "coverArt": Images,
  // Name: GetAlbumById.artists
  "artists": z.array(ArtistInfo),
  // Name: GetAlbumById.tags
  "tags": z.array(z.string()),
  // Name: GetAlbumById.created
  "created": z.number(),
  // Name: GetAlbumById.updated
  "updated": z.number(),
});
export type GetAlbumById = z.infer<typeof GetAlbumById>;

// Name: Track
export const Track = z.object({
  // Name: Track.id
  "id": z.string(),
  // Name: Track.name
  "name": z.string(),
  // Name: Track.duration
  "duration": z.number(),
  // Name: Track.number
  "number": z.number().nullable(),
  // Name: Track.year
  "year": z.number().nullable(),
  // Name: Track.coverArt
  "coverArt": Images,
  // Name: Track.albumId
  "albumId": z.string(),
  // Name: Track.albumName
  "albumName": z.string(),
  // Name: Track.artists
  "artists": z.array(ArtistInfo),
  // Name: Track.tags
  "tags": z.array(z.string()),
  // Name: Track.created
  "created": z.number(),
  // Name: Track.updated
  "updated": z.number(),
});
export type Track = z.infer<typeof Track>;

// Name: GetAlbumTracks
export const GetAlbumTracks = z.object({
  // Name: GetAlbumTracks.tracks
  "tracks": z.array(Track),
});
export type GetAlbumTracks = z.infer<typeof GetAlbumTracks>;

// Name: Page
export const Page = z.object({
  // Name: Page.page
  "page": z.number(),
  // Name: Page.perPage
  "perPage": z.number(),
  // Name: Page.totalItems
  "totalItems": z.number(),
  // Name: Page.totalPages
  "totalPages": z.number(),
});
export type Page = z.infer<typeof Page>;

// Name: GetAlbums
export const GetAlbums = z.object({
  // Name: GetAlbums.page
  "page": Page,
  // Name: GetAlbums.albums
  "albums": z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

// Name: GetAllApiTokens
export const GetAllApiTokens = z.object({
  // Name: GetAllApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetAllApiTokens = z.infer<typeof GetAllApiTokens>;

// Name: GetArtistAlbumsById
export const GetArtistAlbumsById = z.object({
  // Name: GetArtistAlbumsById.albums
  "albums": z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

// Name: GetArtistById
export const GetArtistById = z.object({
  // Name: GetArtistById.id
  "id": z.string(),
  // Name: GetArtistById.name
  "name": z.string(),
  // Name: GetArtistById.picture
  "picture": Images,
  // Name: GetArtistById.tags
  "tags": z.array(z.string()),
  // Name: GetArtistById.created
  "created": z.number(),
  // Name: GetArtistById.updated
  "updated": z.number(),
});
export type GetArtistById = z.infer<typeof GetArtistById>;

// Name: GetArtists
export const GetArtists = z.object({
  // Name: GetArtists.page
  "page": Page,
  // Name: GetArtists.artists
  "artists": z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

// Name: GetAuthProviders
export const GetAuthProviders = z.object({
  // Name: GetAuthProviders.providers
  "providers": z.array(AuthProvider),
});
export type GetAuthProviders = z.infer<typeof GetAuthProviders>;

// Name: Path
export const Path = z.object({
  // Name: Path.name
  "name": z.string(),
  // Name: Path.path
  "path": z.string(),
  // Name: Path.isDir
  "isDir": z.boolean(),
  // Name: Path.depth
  "depth": z.number(),
});
export type Path = z.infer<typeof Path>;

// Name: GetLibraryPaths
export const GetLibraryPaths = z.object({
  // Name: GetLibraryPaths.paths
  "paths": z.array(Path),
});
export type GetLibraryPaths = z.infer<typeof GetLibraryPaths>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.email
  "email": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.quickPlaylist
  "quickPlaylist": z.string().nullable(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: MediaResource
export const MediaResource = z.object({
  // Name: MediaResource.id
  "id": z.string(),
  // Name: MediaResource.name
  "name": z.string(),
});
export type MediaResource = z.infer<typeof MediaResource>;

// Name: MediaItem
export const MediaItem = z.object({
  // Name: MediaItem.track
  "track": MediaResource,
  // Name: MediaItem.artists
  "artists": z.array(MediaResource),
  // Name: MediaItem.album
  "album": MediaResource,
  // Name: MediaItem.coverArt
  "coverArt": Images,
  // Name: MediaItem.mediaType
  "mediaType": z.string(),
  // Name: MediaItem.mediaUrl
  "mediaUrl": z.string(),
});
export type MediaItem = z.infer<typeof MediaItem>;

// Name: GetMedia
export const GetMedia = z.object({
  // Name: GetMedia.items
  "items": z.array(MediaItem),
});
export type GetMedia = z.infer<typeof GetMedia>;

// Name: GetMediaCommonBody
export const GetMediaCommonBody = z.object({
  // Name: GetMediaCommonBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaCommonBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaCommonBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaCommonBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaCommonBody.offset
  "offset": z.number().optional(),
});
export type GetMediaCommonBody = z.infer<typeof GetMediaCommonBody>;

// Name: GetMediaFromAlbumBody
export const GetMediaFromAlbumBody = z.object({
  // Name: GetMediaFromAlbumBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromAlbumBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromAlbumBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromAlbumBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromAlbumBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromAlbumBody = z.infer<typeof GetMediaFromAlbumBody>;

// Name: GetMediaFromArtistBody
export const GetMediaFromArtistBody = z.object({
  // Name: GetMediaFromArtistBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromArtistBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromArtistBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromArtistBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromArtistBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromArtistBody = z.infer<typeof GetMediaFromArtistBody>;

// Name: GetMediaFromFilterBody
export const GetMediaFromFilterBody = z.object({
  // Name: GetMediaFromFilterBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromFilterBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromFilterBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromFilterBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromFilterBody.offset
  "offset": z.number().optional(),
  // Name: GetMediaFromFilterBody.filter
  "filter": z.string(),
});
export type GetMediaFromFilterBody = z.infer<typeof GetMediaFromFilterBody>;

// Name: GetMediaFromIdsBody
export const GetMediaFromIdsBody = z.object({
  // Name: GetMediaFromIdsBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromIdsBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromIdsBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromIdsBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromIdsBody.offset
  "offset": z.number().optional(),
  // Name: GetMediaFromIdsBody.trackIds
  "trackIds": z.array(z.string()),
  // Name: GetMediaFromIdsBody.keepOrder
  "keepOrder": z.boolean().optional(),
});
export type GetMediaFromIdsBody = z.infer<typeof GetMediaFromIdsBody>;

// Name: GetMediaFromPlaylistBody
export const GetMediaFromPlaylistBody = z.object({
  // Name: GetMediaFromPlaylistBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromPlaylistBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromPlaylistBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromPlaylistBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromPlaylistBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromPlaylistBody = z.infer<typeof GetMediaFromPlaylistBody>;

// Name: GetMediaFromTaglistBody
export const GetMediaFromTaglistBody = z.object({
  // Name: GetMediaFromTaglistBody.mediaType
  "mediaType": z.string().optional(),
  // Name: GetMediaFromTaglistBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: GetMediaFromTaglistBody.sort
  "sort": z.string().optional(),
  // Name: GetMediaFromTaglistBody.limit
  "limit": z.number().optional(),
  // Name: GetMediaFromTaglistBody.offset
  "offset": z.number().optional(),
});
export type GetMediaFromTaglistBody = z.infer<typeof GetMediaFromTaglistBody>;

// Name: GetPlaylistById
export const GetPlaylistById = z.object({
  // Name: GetPlaylistById.id
  "id": z.string(),
  // Name: GetPlaylistById.name
  "name": z.string(),
  // Name: GetPlaylistById.coverArt
  "coverArt": Images,
});
export type GetPlaylistById = z.infer<typeof GetPlaylistById>;

// Name: GetPlaylistItems
export const GetPlaylistItems = z.object({
  // Name: GetPlaylistItems.page
  "page": Page,
  // Name: GetPlaylistItems.items
  "items": z.array(Track),
});
export type GetPlaylistItems = z.infer<typeof GetPlaylistItems>;

// Name: Playlist
export const Playlist = z.object({
  // Name: Playlist.id
  "id": z.string(),
  // Name: Playlist.name
  "name": z.string(),
  // Name: Playlist.coverArt
  "coverArt": Images,
});
export type Playlist = z.infer<typeof Playlist>;

// Name: GetPlaylists
export const GetPlaylists = z.object({
  // Name: GetPlaylists.playlists
  "playlists": z.array(Playlist),
});
export type GetPlaylists = z.infer<typeof GetPlaylists>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: GetTaglistById
export const GetTaglistById = z.object({
  // Name: GetTaglistById.id
  "id": z.string(),
  // Name: GetTaglistById.name
  "name": z.string(),
  // Name: GetTaglistById.filter
  "filter": z.string(),
  // Name: GetTaglistById.created
  "created": z.number(),
  // Name: GetTaglistById.updated
  "updated": z.number(),
});
export type GetTaglistById = z.infer<typeof GetTaglistById>;

// Name: GetTaglistTracks
export const GetTaglistTracks = z.object({
  // Name: GetTaglistTracks.page
  "page": Page,
  // Name: GetTaglistTracks.tracks
  "tracks": z.array(Track),
});
export type GetTaglistTracks = z.infer<typeof GetTaglistTracks>;

// Name: Taglist
export const Taglist = z.object({
  // Name: Taglist.id
  "id": z.string(),
  // Name: Taglist.name
  "name": z.string(),
  // Name: Taglist.filter
  "filter": z.string(),
  // Name: Taglist.created
  "created": z.number(),
  // Name: Taglist.updated
  "updated": z.number(),
});
export type Taglist = z.infer<typeof Taglist>;

// Name: GetTaglists
export const GetTaglists = z.object({
  // Name: GetTaglists.taglists
  "taglists": z.array(Taglist),
});
export type GetTaglists = z.infer<typeof GetTaglists>;

// Name: GetTrackById
export const GetTrackById = z.object({
  // Name: GetTrackById.id
  "id": z.string(),
  // Name: GetTrackById.name
  "name": z.string(),
  // Name: GetTrackById.duration
  "duration": z.number(),
  // Name: GetTrackById.number
  "number": z.number().nullable(),
  // Name: GetTrackById.year
  "year": z.number().nullable(),
  // Name: GetTrackById.coverArt
  "coverArt": Images,
  // Name: GetTrackById.albumId
  "albumId": z.string(),
  // Name: GetTrackById.albumName
  "albumName": z.string(),
  // Name: GetTrackById.artists
  "artists": z.array(ArtistInfo),
  // Name: GetTrackById.tags
  "tags": z.array(z.string()),
  // Name: GetTrackById.created
  "created": z.number(),
  // Name: GetTrackById.updated
  "updated": z.number(),
});
export type GetTrackById = z.infer<typeof GetTrackById>;

// Name: GetTracks
export const GetTracks = z.object({
  // Name: GetTracks.page
  "page": Page,
  // Name: GetTracks.tracks
  "tracks": z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

// Name: GetUser
export const GetUser = z.object({
  // Name: GetUser.id
  "id": z.string(),
  // Name: GetUser.displayName
  "displayName": z.string(),
});
export type GetUser = z.infer<typeof GetUser>;

// Name: GetUserQuickPlaylistItemIds
export const GetUserQuickPlaylistItemIds = z.object({
  // Name: GetUserQuickPlaylistItemIds.trackIds
  "trackIds": z.array(z.string()),
});
export type GetUserQuickPlaylistItemIds = z.infer<typeof GetUserQuickPlaylistItemIds>;

// Name: PostPlaylistFilterBody
export const PostPlaylistFilterBody = z.object({
  // Name: PostPlaylistFilterBody.name
  "name": z.string(),
  // Name: PostPlaylistFilterBody.filter
  "filter": z.string(),
});
export type PostPlaylistFilterBody = z.infer<typeof PostPlaylistFilterBody>;

// Name: RemovePlaylistItemBody
export const RemovePlaylistItemBody = z.object({
  // Name: RemovePlaylistItemBody.trackId
  "trackId": z.string(),
});
export type RemovePlaylistItemBody = z.infer<typeof RemovePlaylistItemBody>;

// Name: SearchAlbums
export const SearchAlbums = z.object({
  // Name: SearchAlbums.albums
  "albums": z.array(Album),
});
export type SearchAlbums = z.infer<typeof SearchAlbums>;

// Name: SearchArtists
export const SearchArtists = z.object({
  // Name: SearchArtists.artists
  "artists": z.array(Artist),
});
export type SearchArtists = z.infer<typeof SearchArtists>;

// Name: SearchTracks
export const SearchTracks = z.object({
  // Name: SearchTracks.tracks
  "tracks": z.array(Track),
});
export type SearchTracks = z.infer<typeof SearchTracks>;

// Name: SyncLibraryBody
export const SyncLibraryBody = z.object({
  // Name: SyncLibraryBody.path
  "path": z.string().optional(),
});
export type SyncLibraryBody = z.infer<typeof SyncLibraryBody>;

// Name: TrackId
export const TrackId = z.object({
  // Name: TrackId.trackId
  "trackId": z.string(),
});
export type TrackId = z.infer<typeof TrackId>;

// Name: UpdateTaglistBody
export const UpdateTaglistBody = z.object({
  // Name: UpdateTaglistBody.name
  "name": z.string().nullable().optional(),
  // Name: UpdateTaglistBody.filter
  "filter": z.string().nullable().optional(),
});
export type UpdateTaglistBody = z.infer<typeof UpdateTaglistBody>;

// Name: UpdateUserSettingsBody
export const UpdateUserSettingsBody = z.object({
  // Name: UpdateUserSettingsBody.quickPlaylist
  "quickPlaylist": z.string().nullable().optional(),
});
export type UpdateUserSettingsBody = z.infer<typeof UpdateUserSettingsBody>;

