// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api


func (c *Client) AddItemToPlaylist(id string, body AddItemToPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AddPlaylistFilter(playlistId string, body AddPlaylistFilterBody, options Options) (*AddPlaylistFilter, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AddPlaylistFilter](data, body)
}

func (c *Client) AddToUserQuickPlaylist(body TrackId, options Options) (*any, error) {
	path := "/api/v1/user/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}


func (c *Client) AuthClaimQuickConnectCode(body AuthClaimQuickConnectCodeBody, options Options) (*any, error) {
	path := "/api/v1/auth/quick-connect/claim"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AuthFinishProvider(body AuthFinishProviderBody, options Options) (*AuthFinishProvider, error) {
	path := "/api/v1/auth/providers/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishProvider](data, body)
}

func (c *Client) AuthFinishQuickConnect(body AuthFinishQuickConnectBody, options Options) (*AuthFinishQuickConnect, error) {
	path := "/api/v1/auth/quick-connect/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishQuickConnect](data, body)
}

func (c *Client) AuthGetProviderStatus(body AuthGetProviderStatusBody, options Options) (*AuthGetProviderStatus, error) {
	path := "/api/v1/auth/provider/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetProviderStatus](data, body)
}

func (c *Client) AuthGetProviders(options Options) (*GetAuthProviders, error) {
	path := "/api/v1/auth/providers"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAuthProviders](data, nil)
}

func (c *Client) AuthGetQuickConnectStatus(body AuthGetQuickConnectStatusBody, options Options) (*AuthGetQuickConnectStatus, error) {
	path := "/api/v1/auth/quick-connect/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetQuickConnectStatus](data, body)
}

func (c *Client) AuthProviderInitiate(body AuthInitiateBody, options Options) (*AuthInitiate, error) {
	path := "/api/v1/auth/providers/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthInitiate](data, body)
}

func (c *Client) AuthQuickConnectInitiate(options Options) (*AuthQuickConnectInitiate, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthQuickConnectInitiate](data, nil)
}

func (c *Client) ClearPlaylist(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items/all", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) CreateApiToken(body CreateApiTokenBody, options Options) (*CreateApiToken, error) {
	path := "/api/v1/user/apitoken"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateApiToken](data, body)
}

func (c *Client) CreatePlaylist(body CreatePlaylistBody, options Options) (*CreatePlaylist, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreatePlaylist](data, body)
}

func (c *Client) CreatePlaylistFromFilter(body PostPlaylistFilterBody, options Options) (*CreatePlaylist, error) {
	path := "/api/v1/playlists/filter"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreatePlaylist](data, body)
}

func (c *Client) CreateVirtualPlaylist(body CreateVirtualPlaylistBody, options Options) (*CreateVirtualPlaylist, error) {
	path := "/api/v1/virtual-playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateVirtualPlaylist](data, body)
}

func (c *Client) DeleteApiToken(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/apitoken/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeletePlaylist(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeleteVirtualPlaylist(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) EditPlaylist(id string, body EditPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) EditPlaylistFilter(playlistId string, filterId string, body EditPlaylistFilterBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/filters/%v", playlistId, filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) GeneratePlaylistImage(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) GetAlbumById(id string, options Options) (*GetAlbumById, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumById](data, nil)
}


func (c *Client) GetAlbumTracks(id string, options Options) (*GetAlbumTracks, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumTracks](data, nil)
}

func (c *Client) GetAlbums(options Options) (*GetAlbums, error) {
	path := "/api/v1/albums"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbums](data, nil)
}

func (c *Client) GetAllApiTokens(options Options) (*GetAllApiTokens, error) {
	path := "/api/v1/user/apitoken"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAllApiTokens](data, nil)
}

func (c *Client) GetArtistAlbums(id string, options Options) (*GetArtistAlbumsById, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistAlbumsById](data, nil)
}

func (c *Client) GetArtistById(id string, options Options) (*GetArtistById, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistById](data, nil)
}


func (c *Client) GetArtists(options Options) (*GetArtists, error) {
	path := "/api/v1/artists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtists](data, nil)
}

func (c *Client) GetMe(options Options) (*GetMe, error) {
	path := "/api/v1/auth/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMe](data, nil)
}

func (c *Client) GetMediaFromAlbum(albumId string, body GetMediaFromAlbumBody, options Options) (*GetMedia, error) {
	path := Sprintf("/api/v1/media/album/%v", albumId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromArtist(artistId string, body GetMediaFromArtistBody, options Options) (*GetMedia, error) {
	path := Sprintf("/api/v1/media/artist/%v", artistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromFilter(body GetMediaFromFilterBody, options Options) (*GetMedia, error) {
	path := "/api/v1/media/filter"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromIds(body GetMediaFromIdsBody, options Options) (*GetMedia, error) {
	path := "/api/v1/media/ids"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromPlaylist(playlistId string, body GetMediaFromPlaylistBody, options Options) (*GetMedia, error) {
	path := Sprintf("/api/v1/media/playlist/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaSettings(options Options) (*GetMediaSettings, error) {
	path := "/api/v1/media/settings"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMediaSettings](data, nil)
}

func (c *Client) GetPlaylistById(id string, options Options) (*GetPlaylistById, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistById](data, nil)
}

func (c *Client) GetPlaylistFilters(playlistId string, options Options) (*GetPlaylistFilters, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistFilters](data, nil)
}


func (c *Client) GetPlaylistItems(id string, options Options) (*GetPlaylistItems, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistItems](data, nil)
}

func (c *Client) GetPlaylists(options Options) (*GetPlaylists, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylists](data, nil)
}

func (c *Client) GetSystemInfo(options Options) (*GetSystemInfo, error) {
	path := "/api/v1/system/info"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetSystemInfo](data, nil)
}

func (c *Client) GetTrackById(id string, options Options) (*GetTrackById, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTrackById](data, nil)
}

func (c *Client) GetTracks(options Options) (*GetTracks, error) {
	path := "/api/v1/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTracks](data, nil)
}

func (c *Client) GetUser(id string, options Options) (*GetUser, error) {
	path := Sprintf("/api/v1/users/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUser](data, nil)
}

func (c *Client) GetUserQuickPlaylistItemIds(options Options) (*GetUserQuickPlaylistItemIds, error) {
	path := "/api/v1/user/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUserQuickPlaylistItemIds](data, nil)
}

func (c *Client) GetVirtualPlaylistById(id string, options Options) (*GetVirtualPlaylistById, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetVirtualPlaylistById](data, nil)
}

func (c *Client) GetVirtualPlaylistTracks(id string, options Options) (*GetVirtualPlaylistTracks, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v/tracks", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetVirtualPlaylistTracks](data, nil)
}

func (c *Client) GetVirtualPlaylists(options Options) (*GetVirtualPlaylists, error) {
	path := "/api/v1/virtual-playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetVirtualPlaylists](data, nil)
}

func (c *Client) GetVirtualPlaylistsForPlaylist(playlistId string, options Options) (*GetVirtualPlaylists, error) {
	path := Sprintf("/api/v1/virtual-playlists/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetVirtualPlaylists](data, nil)
}

func (c *Client) RemoveItemFromUserQuickPlaylist(body TrackId, options Options) (*any, error) {
	path := "/api/v1/user/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) RemovePlaylistItem(id string, body RemovePlaylistItemBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) SearchAlbums(options Options) (*SearchAlbums, error) {
	path := "/api/v1/albums/search"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchAlbums](data, nil)
}

func (c *Client) SearchArtists(options Options) (*SearchArtists, error) {
	path := "/api/v1/artists/search"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchArtists](data, nil)
}

func (c *Client) SearchTracks(options Options) (*SearchTracks, error) {
	path := "/api/v1/tracks/search"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchTracks](data, nil)
}



func (c *Client) SyncLibrary(options Options) (*any, error) {
	path := "/api/v1/system/library"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) UpdateUserSettings(body UpdateUserSettingsBody, options Options) (*any, error) {
	path := "/api/v1/user/settings"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) UpdateVirtualPlaylist(id string, body UpdateVirtualPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *ClientUrls) AddItemToPlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	return c.getUrl(path)
}

func (c *ClientUrls) AddPlaylistFilter(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) AddToUserQuickPlaylist() (*URL, error) {
	path := "/api/v1/user/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthCallback() (*URL, error) {
	path := "/api/v1/auth/providers/callback"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthClaimQuickConnectCode() (*URL, error) {
	path := "/api/v1/auth/quick-connect/claim"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishProvider() (*URL, error) {
	path := "/api/v1/auth/providers/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishQuickConnect() (*URL, error) {
	path := "/api/v1/auth/quick-connect/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviderStatus() (*URL, error) {
	path := "/api/v1/auth/provider/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviders() (*URL, error) {
	path := "/api/v1/auth/providers"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetQuickConnectStatus() (*URL, error) {
	path := "/api/v1/auth/quick-connect/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthProviderInitiate() (*URL, error) {
	path := "/api/v1/auth/providers/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthQuickConnectInitiate() (*URL, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) ClearPlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items/all", id)
	return c.getUrl(path)
}

func (c *ClientUrls) CreateApiToken() (*URL, error) {
	path := "/api/v1/user/apitoken"
	return c.getUrl(path)
}

func (c *ClientUrls) CreatePlaylist() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) CreatePlaylistFromFilter() (*URL, error) {
	path := "/api/v1/playlists/filter"
	return c.getUrl(path)
}

func (c *ClientUrls) CreateVirtualPlaylist() (*URL, error) {
	path := "/api/v1/virtual-playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteApiToken(id string) (*URL, error) {
	path := Sprintf("/api/v1/user/apitoken/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) DeletePlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteVirtualPlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) EditPlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) EditPlaylistFilter(playlistId string, filterId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters/%v", playlistId, filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) GeneratePlaylistImage(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumById(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumImage(albumId string, image string) (*URL, error) {
	path := Sprintf("/files/albums/images/%v/%v", albumId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumTracks(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbums() (*URL, error) {
	path := "/api/v1/albums"
	return c.getUrl(path)
}

func (c *ClientUrls) GetAllApiTokens() (*URL, error) {
	path := "/api/v1/user/apitoken"
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistAlbums(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistById(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistImage(artistId string, image string) (*URL, error) {
	path := Sprintf("/files/artists/images/%v/%v", artistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtists() (*URL, error) {
	path := "/api/v1/artists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMe() (*URL, error) {
	path := "/api/v1/auth/me"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromAlbum(albumId string) (*URL, error) {
	path := Sprintf("/api/v1/media/album/%v", albumId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromArtist(artistId string) (*URL, error) {
	path := Sprintf("/api/v1/media/artist/%v", artistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromFilter() (*URL, error) {
	path := "/api/v1/media/filter"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromIds() (*URL, error) {
	path := "/api/v1/media/ids"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/media/playlist/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaSettings() (*URL, error) {
	path := "/api/v1/media/settings"
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistById(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistFilters(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistImage(playlistId string, image string) (*URL, error) {
	path := Sprintf("/files/playlists/images/%v/%v", playlistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistItems(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylists() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetSystemInfo() (*URL, error) {
	path := "/api/v1/system/info"
	return c.getUrl(path)
}

func (c *ClientUrls) GetTrackById(id string) (*URL, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetTracks() (*URL, error) {
	path := "/api/v1/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUser(id string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserQuickPlaylistItemIds() (*URL, error) {
	path := "/api/v1/user/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) GetVirtualPlaylistById(id string) (*URL, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetVirtualPlaylistTracks(id string) (*URL, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v/tracks", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetVirtualPlaylists() (*URL, error) {
	path := "/api/v1/virtual-playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetVirtualPlaylistsForPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/virtual-playlists/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) RemoveItemFromUserQuickPlaylist() (*URL, error) {
	path := "/api/v1/user/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) RemovePlaylistItem(id string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", id)
	return c.getUrl(path)
}

func (c *ClientUrls) SearchAlbums() (*URL, error) {
	path := "/api/v1/albums/search"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchArtists() (*URL, error) {
	path := "/api/v1/artists/search"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchTracks() (*URL, error) {
	path := "/api/v1/tracks/search"
	return c.getUrl(path)
}

func (c *ClientUrls) SseHandler() (*URL, error) {
	path := "/api/v1/system/sse"
	return c.getUrl(path)
}

func (c *ClientUrls) StreamTrack(trackId string) (*URL, error) {
	path := Sprintf("/media/tracks/%v/stream", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) SyncLibrary() (*URL, error) {
	path := "/api/v1/system/library"
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateUserSettings() (*URL, error) {
	path := "/api/v1/user/settings"
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateVirtualPlaylist(id string) (*URL, error) {
	path := Sprintf("/api/v1/virtual-playlists/%v", id)
	return c.getUrl(path)
}
