// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

// Name: AddItemToPlaylistBody
type AddItemToPlaylistBody struct {
	// Name: AddItemToPlaylistBody.trackId
	TrackId string `json:"trackId"`
}

// Name: AddPlaylistFilter
type AddPlaylistFilter struct {
	// Name: AddPlaylistFilter.filterId
	FilterId string `json:"filterId"`
}

// Name: AddPlaylistFilterBody
type AddPlaylistFilterBody struct {
	// Name: AddPlaylistFilterBody.name
	Name string `json:"name"`
	// Name: AddPlaylistFilterBody.filter
	Filter string `json:"filter"`
}

// Name: Images
type Images struct {
	// Name: Images.original
	Original string `json:"original"`
	// Name: Images.small
	Small string `json:"small"`
	// Name: Images.medium
	Medium string `json:"medium"`
	// Name: Images.large
	Large string `json:"large"`
}

// Name: ArtistInfo
type ArtistInfo struct {
	// Name: ArtistInfo.id
	Id string `json:"id"`
	// Name: ArtistInfo.name
	Name string `json:"name"`
}

// Name: Album
type Album struct {
	// Name: Album.id
	Id string `json:"id"`
	// Name: Album.name
	Name string `json:"name"`
	// Name: Album.year
	Year *int `json:"year,omitempty"`
	// Name: Album.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Album.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: Album.tags
	Tags []string `json:"tags"`
	// Name: Album.created
	Created int `json:"created"`
	// Name: Album.updated
	Updated int `json:"updated"`
}

// Name: ApiToken
type ApiToken struct {
	// Name: ApiToken.id
	Id string `json:"id"`
	// Name: ApiToken.name
	Name string `json:"name"`
}

// Name: Artist
type Artist struct {
	// Name: Artist.id
	Id string `json:"id"`
	// Name: Artist.name
	Name string `json:"name"`
	// Name: Artist.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Artist.tags
	Tags []string `json:"tags"`
	// Name: Artist.created
	Created int `json:"created"`
	// Name: Artist.updated
	Updated int `json:"updated"`
}

// Name: AuthClaimQuickConnectCodeBody
type AuthClaimQuickConnectCodeBody struct {
	// Name: AuthClaimQuickConnectCodeBody.code
	Code string `json:"code"`
}

// Name: AuthFinishProvider
type AuthFinishProvider struct {
	// Name: AuthFinishProvider.token
	Token string `json:"token"`
}

// Name: AuthFinishProviderBody
type AuthFinishProviderBody struct {
	// Name: AuthFinishProviderBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthFinishProviderBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthFinishQuickConnect
type AuthFinishQuickConnect struct {
	// Name: AuthFinishQuickConnect.token
	Token string `json:"token"`
}

// Name: AuthFinishQuickConnectBody
type AuthFinishQuickConnectBody struct {
	// Name: AuthFinishQuickConnectBody.code
	Code string `json:"code"`
	// Name: AuthFinishQuickConnectBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetProviderStatus
type AuthGetProviderStatus struct {
	// Name: AuthGetProviderStatus.status
	Status string `json:"status"`
}

// Name: AuthGetProviderStatusBody
type AuthGetProviderStatusBody struct {
	// Name: AuthGetProviderStatusBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthGetProviderStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetQuickConnectStatus
type AuthGetQuickConnectStatus struct {
	// Name: AuthGetQuickConnectStatus.status
	Status string `json:"status"`
}

// Name: AuthGetQuickConnectStatusBody
type AuthGetQuickConnectStatusBody struct {
	// Name: AuthGetQuickConnectStatusBody.code
	Code string `json:"code"`
	// Name: AuthGetQuickConnectStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthInitiate
type AuthInitiate struct {
	// Name: AuthInitiate.requestId
	RequestId string `json:"requestId"`
	// Name: AuthInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: AuthInitiateBody
type AuthInitiateBody struct {
	// Name: AuthInitiateBody.providerId
	ProviderId string `json:"providerId"`
}

// Name: AuthProvider
type AuthProvider struct {
	// Name: AuthProvider.id
	Id string `json:"id"`
	// Name: AuthProvider.displayName
	DisplayName string `json:"displayName"`
}

// Name: AuthQuickConnectInitiate
type AuthQuickConnectInitiate struct {
	// Name: AuthQuickConnectInitiate.code
	Code string `json:"code"`
	// Name: AuthQuickConnectInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthQuickConnectInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthQuickConnectInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: CreateApiToken
type CreateApiToken struct {
	// Name: CreateApiToken.token
	Token string `json:"token"`
}

// Name: CreateApiTokenBody
type CreateApiTokenBody struct {
	// Name: CreateApiTokenBody.name
	Name string `json:"name"`
}

// Name: CreatePlaylist
type CreatePlaylist struct {
	// Name: CreatePlaylist.id
	Id string `json:"id"`
}

// Name: CreatePlaylistBody
type CreatePlaylistBody struct {
	// Name: CreatePlaylistBody.name
	Name string `json:"name"`
}

// Name: CreateTrackFilter
type CreateTrackFilter struct {
	// Name: CreateTrackFilter.filterId
	FilterId string `json:"filterId"`
}

// Name: CreateTrackFilterBody
type CreateTrackFilterBody struct {
	// Name: CreateTrackFilterBody.name
	Name string `json:"name"`
	// Name: CreateTrackFilterBody.filter
	Filter string `json:"filter"`
}

// Name: EditPlaylistBody
type EditPlaylistBody struct {
	// Name: EditPlaylistBody.name
	Name *string `json:"name,omitempty"`
	// Name: EditPlaylistBody.coverUrl
	CoverUrl *string `json:"coverUrl,omitempty"`
}

// Name: EditPlaylistFilterBody
type EditPlaylistFilterBody struct {
	// Name: EditPlaylistFilterBody.name
	Name *string `json:"name,omitempty"`
	// Name: EditPlaylistFilterBody.filter
	Filter *string `json:"filter,omitempty"`
}

// Name: EditTrackFilterBody
type EditTrackFilterBody struct {
	// Name: EditTrackFilterBody.name
	Name *string `json:"name,omitempty"`
	// Name: EditTrackFilterBody.filter
	Filter *string `json:"filter,omitempty"`
}

// Name: EditUserBody
type EditUserBody struct {
	// Name: EditUserBody.displayName
	DisplayName *string `json:"displayName,omitempty"`
}

// Name: GetAlbumById
type GetAlbumById struct {
	// Name: GetAlbumById.id
	Id string `json:"id"`
	// Name: GetAlbumById.name
	Name string `json:"name"`
	// Name: GetAlbumById.year
	Year *int `json:"year,omitempty"`
	// Name: GetAlbumById.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: GetAlbumById.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: GetAlbumById.tags
	Tags []string `json:"tags"`
	// Name: GetAlbumById.created
	Created int `json:"created"`
	// Name: GetAlbumById.updated
	Updated int `json:"updated"`
}

// Name: Track
type Track struct {
	// Name: Track.id
	Id string `json:"id"`
	// Name: Track.name
	Name string `json:"name"`
	// Name: Track.order
	Order *int `json:"order,omitempty"`
	// Name: Track.duration
	Duration int `json:"duration"`
	// Name: Track.number
	Number *int `json:"number,omitempty"`
	// Name: Track.year
	Year *int `json:"year,omitempty"`
	// Name: Track.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Track.albumId
	AlbumId string `json:"albumId"`
	// Name: Track.albumName
	AlbumName string `json:"albumName"`
	// Name: Track.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: Track.tags
	Tags []string `json:"tags"`
	// Name: Track.created
	Created int `json:"created"`
	// Name: Track.updated
	Updated int `json:"updated"`
}

// Name: GetAlbumTracks
type GetAlbumTracks struct {
	// Name: GetAlbumTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: Page
type Page struct {
	// Name: Page.page
	Page int `json:"page"`
	// Name: Page.perPage
	PerPage int `json:"perPage"`
	// Name: Page.totalItems
	TotalItems int `json:"totalItems"`
	// Name: Page.totalPages
	TotalPages int `json:"totalPages"`
}

// Name: GetAlbums
type GetAlbums struct {
	// Name: GetAlbums.page
	Page Page `json:"page"`
	// Name: GetAlbums.albums
	Albums []Album `json:"albums"`
}

// Name: GetAllApiTokens
type GetAllApiTokens struct {
	// Name: GetAllApiTokens.tokens
	Tokens []ApiToken `json:"tokens"`
}

// Name: GetArtistAlbumsById
type GetArtistAlbumsById struct {
	// Name: GetArtistAlbumsById.albums
	Albums []Album `json:"albums"`
}

// Name: GetArtistById
type GetArtistById struct {
	// Name: GetArtistById.artist
	Artist Artist `json:"artist"`
}

// Name: GetArtists
type GetArtists struct {
	// Name: GetArtists.page
	Page Page `json:"page"`
	// Name: GetArtists.artists
	Artists []Artist `json:"artists"`
}

// Name: GetAuthProviders
type GetAuthProviders struct {
	// Name: GetAuthProviders.providers
	Providers []AuthProvider `json:"providers"`
}

// Name: GetMe
type GetMe struct {
	// Name: GetMe.id
	Id string `json:"id"`
	// Name: GetMe.email
	Email string `json:"email"`
	// Name: GetMe.displayName
	DisplayName string `json:"displayName"`
	// Name: GetMe.role
	Role string `json:"role"`
	// Name: GetMe.picture
	Picture Images `json:"picture"`
	// Name: GetMe.quickPlaylist
	QuickPlaylist *string `json:"quickPlaylist,omitempty"`
}

// Name: MediaResource
type MediaResource struct {
	// Name: MediaResource.id
	Id string `json:"id"`
	// Name: MediaResource.name
	Name string `json:"name"`
}

// Name: MediaItem
type MediaItem struct {
	// Name: MediaItem.track
	Track MediaResource `json:"track"`
	// Name: MediaItem.artists
	Artists []MediaResource `json:"artists"`
	// Name: MediaItem.album
	Album MediaResource `json:"album"`
	// Name: MediaItem.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: MediaItem.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: MediaItem.mediaUrl
	MediaUrl string `json:"mediaUrl"`
}

// Name: GetMedia
type GetMedia struct {
	// Name: GetMedia.items
	Items []MediaItem `json:"items"`
}

// Name: GetMediaCommonBody
type GetMediaCommonBody struct {
	// Name: GetMediaCommonBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaCommonBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaCommonBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaCommonBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaCommonBody.offset
	Offset int `json:"offset"`
}

// Name: GetMediaFromAlbumBody
type GetMediaFromAlbumBody struct {
	// Name: GetMediaFromAlbumBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaFromAlbumBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaFromAlbumBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaFromAlbumBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaFromAlbumBody.offset
	Offset int `json:"offset"`
}

// Name: GetMediaFromArtistBody
type GetMediaFromArtistBody struct {
	// Name: GetMediaFromArtistBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaFromArtistBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaFromArtistBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaFromArtistBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaFromArtistBody.offset
	Offset int `json:"offset"`
}

// Name: GetMediaFromFilterBody
type GetMediaFromFilterBody struct {
	// Name: GetMediaFromFilterBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaFromFilterBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaFromFilterBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaFromFilterBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaFromFilterBody.offset
	Offset int `json:"offset"`
	// Name: GetMediaFromFilterBody.filter
	Filter string `json:"filter"`
}

// Name: GetMediaFromIdsBody
type GetMediaFromIdsBody struct {
	// Name: GetMediaFromIdsBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaFromIdsBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaFromIdsBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaFromIdsBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaFromIdsBody.offset
	Offset int `json:"offset"`
	// Name: GetMediaFromIdsBody.trackIds
	TrackIds []string `json:"trackIds"`
	// Name: GetMediaFromIdsBody.keepOrder
	KeepOrder bool `json:"keepOrder"`
}

// Name: GetMediaFromPlaylistBody
type GetMediaFromPlaylistBody struct {
	// Name: GetMediaFromPlaylistBody.mediaFormat
	MediaFormat string `json:"mediaFormat"`
	// Name: GetMediaFromPlaylistBody.shuffle
	Shuffle bool `json:"shuffle"`
	// Name: GetMediaFromPlaylistBody.sort
	Sort string `json:"sort"`
	// Name: GetMediaFromPlaylistBody.limit
	Limit int `json:"limit"`
	// Name: GetMediaFromPlaylistBody.offset
	Offset int `json:"offset"`
	// Name: GetMediaFromPlaylistBody.filterId
	FilterId string `json:"filterId"`
}

// Name: MediaFormat
type MediaFormat struct {
	// Name: MediaFormat.name
	Name string `json:"name"`
	// Name: MediaFormat.format
	Format string `json:"format"`
	// Name: MediaFormat.ext
	Ext string `json:"ext"`
	// Name: MediaFormat.qualityHighBitrate
	QualityHighBitrate int `json:"qualityHighBitrate"`
	// Name: MediaFormat.qualityMediumBitrate
	QualityMediumBitrate int `json:"qualityMediumBitrate"`
	// Name: MediaFormat.qualityLowBitrate
	QualityLowBitrate int `json:"qualityLowBitrate"`
	// Name: MediaFormat.order
	Order int `json:"order"`
}

// Name: MediaDeviceSpec
type MediaDeviceSpec struct {
	// Name: MediaDeviceSpec.name
	Name string `json:"name"`
	// Name: MediaDeviceSpec.preferedFormat
	PreferedFormat string `json:"preferedFormat"`
	// Name: MediaDeviceSpec.allowedFormats
	AllowedFormats []string `json:"allowedFormats"`
}

// Name: GetMediaSettings
type GetMediaSettings struct {
	// Name: GetMediaSettings.formats
	Formats []MediaFormat `json:"formats"`
	// Name: GetMediaSettings.deviceSpecs
	DeviceSpecs []MediaDeviceSpec `json:"deviceSpecs"`
}

// Name: GetPlaylistById
type GetPlaylistById struct {
	// Name: GetPlaylistById.id
	Id string `json:"id"`
	// Name: GetPlaylistById.name
	Name string `json:"name"`
	// Name: GetPlaylistById.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: GetPlaylistById.trackCount
	TrackCount int `json:"trackCount"`
}

// Name: PlaylistFilter
type PlaylistFilter struct {
	// Name: PlaylistFilter.filterId
	FilterId string `json:"filterId"`
	// Name: PlaylistFilter.playlistId
	PlaylistId string `json:"playlistId"`
	// Name: PlaylistFilter.name
	Name string `json:"name"`
	// Name: PlaylistFilter.filter
	Filter string `json:"filter"`
}

// Name: GetPlaylistFilters
type GetPlaylistFilters struct {
	// Name: GetPlaylistFilters.filters
	Filters []PlaylistFilter `json:"filters"`
}

// Name: GetPlaylistItems
type GetPlaylistItems struct {
	// Name: GetPlaylistItems.page
	Page Page `json:"page"`
	// Name: GetPlaylistItems.items
	Items []Track `json:"items"`
}

// Name: Playlist
type Playlist struct {
	// Name: Playlist.id
	Id string `json:"id"`
	// Name: Playlist.name
	Name string `json:"name"`
	// Name: Playlist.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Playlist.trackCount
	TrackCount int `json:"trackCount"`
}

// Name: GetPlaylists
type GetPlaylists struct {
	// Name: GetPlaylists.playlists
	Playlists []Playlist `json:"playlists"`
}

// Name: GetSystemInfo
type GetSystemInfo struct {
	// Name: GetSystemInfo.version
	Version string `json:"version"`
}

// Name: GetTrackById
type GetTrackById struct {
	// Name: GetTrackById.id
	Id string `json:"id"`
	// Name: GetTrackById.name
	Name string `json:"name"`
	// Name: GetTrackById.order
	Order *int `json:"order,omitempty"`
	// Name: GetTrackById.duration
	Duration int `json:"duration"`
	// Name: GetTrackById.number
	Number *int `json:"number,omitempty"`
	// Name: GetTrackById.year
	Year *int `json:"year,omitempty"`
	// Name: GetTrackById.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: GetTrackById.albumId
	AlbumId string `json:"albumId"`
	// Name: GetTrackById.albumName
	AlbumName string `json:"albumName"`
	// Name: GetTrackById.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: GetTrackById.tags
	Tags []string `json:"tags"`
	// Name: GetTrackById.created
	Created int `json:"created"`
	// Name: GetTrackById.updated
	Updated int `json:"updated"`
}

// Name: TrackFilter
type TrackFilter struct {
	// Name: TrackFilter.filterId
	FilterId string `json:"filterId"`
	// Name: TrackFilter.userId
	UserId string `json:"userId"`
	// Name: TrackFilter.name
	Name string `json:"name"`
	// Name: TrackFilter.filter
	Filter string `json:"filter"`
}

// Name: GetTrackFilters
type GetTrackFilters struct {
	// Name: GetTrackFilters.filters
	Filters []TrackFilter `json:"filters"`
}

// Name: GetTracks
type GetTracks struct {
	// Name: GetTracks.page
	Page Page `json:"page"`
	// Name: GetTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: GetUser
type GetUser struct {
	// Name: GetUser.id
	Id string `json:"id"`
	// Name: GetUser.displayName
	DisplayName string `json:"displayName"`
	// Name: GetUser.picture
	Picture Images `json:"picture"`
}

// Name: GetUserQuickPlaylistItemIds
type GetUserQuickPlaylistItemIds struct {
	// Name: GetUserQuickPlaylistItemIds.trackIds
	TrackIds []string `json:"trackIds"`
}

// Name: RecordTrackBody
type RecordTrackBody struct {
	// Name: RecordTrackBody.duration
	Duration float32 `json:"duration"`
	// Name: RecordTrackBody.source
	Source string `json:"source"`
}

// Name: RemovePlaylistItemBody
type RemovePlaylistItemBody struct {
	// Name: RemovePlaylistItemBody.trackId
	TrackId string `json:"trackId"`
}

// Name: ReorderPlaylistItemsBody
type ReorderPlaylistItemsBody struct {
	// Name: ReorderPlaylistItemsBody.before
	Before bool `json:"before"`
	// Name: ReorderPlaylistItemsBody.anchorTrackId
	AnchorTrackId string `json:"anchorTrackId"`
	// Name: ReorderPlaylistItemsBody.trackIds
	TrackIds []string `json:"trackIds"`
}

// Name: SearchAlbums
type SearchAlbums struct {
	// Name: SearchAlbums.albums
	Albums []Album `json:"albums"`
}

// Name: SearchArtists
type SearchArtists struct {
	// Name: SearchArtists.artists
	Artists []Artist `json:"artists"`
}

// Name: SearchTracks
type SearchTracks struct {
	// Name: SearchTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: TrackId
type TrackId struct {
	// Name: TrackId.trackId
	TrackId string `json:"trackId"`
}

// Name: UpdateUserSettingsBody
type UpdateUserSettingsBody struct {
	// Name: UpdateUserSettingsBody.quickPlaylist
	QuickPlaylist *string `json:"quickPlaylist,omitempty"`
}

