// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: AddAlbumToQueueBody
export const AddAlbumToQueueBody = z.object({
  // Name: AddAlbumToQueueBody.filterId
  "filterId": z.string().optional(),
  // Name: AddAlbumToQueueBody.position
  "position": z.string(),
  // Name: AddAlbumToQueueBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddAlbumToQueueBody.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddAlbumToQueueBody.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
});
export type AddAlbumToQueueBody = z.infer<typeof AddAlbumToQueueBody>;

// Name: AddArtistToQueueBody
export const AddArtistToQueueBody = z.object({
  // Name: AddArtistToQueueBody.filterId
  "filterId": z.string().optional(),
  // Name: AddArtistToQueueBody.position
  "position": z.string(),
  // Name: AddArtistToQueueBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddArtistToQueueBody.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddArtistToQueueBody.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
});
export type AddArtistToQueueBody = z.infer<typeof AddArtistToQueueBody>;

// Name: AddFavoritesToQueueBody
export const AddFavoritesToQueueBody = z.object({
  // Name: AddFavoritesToQueueBody.filterId
  "filterId": z.string().optional(),
  // Name: AddFavoritesToQueueBody.position
  "position": z.string(),
  // Name: AddFavoritesToQueueBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddFavoritesToQueueBody.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddFavoritesToQueueBody.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
});
export type AddFavoritesToQueueBody = z.infer<typeof AddFavoritesToQueueBody>;

// Name: AddItemToPlaylistBody
export const AddItemToPlaylistBody = z.object({
  // Name: AddItemToPlaylistBody.trackId
  "trackId": z.string(),
});
export type AddItemToPlaylistBody = z.infer<typeof AddItemToPlaylistBody>;

// Name: AddPlaylistToQueueBody
export const AddPlaylistToQueueBody = z.object({
  // Name: AddPlaylistToQueueBody.filterId
  "filterId": z.string().optional(),
  // Name: AddPlaylistToQueueBody.position
  "position": z.string(),
  // Name: AddPlaylistToQueueBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddPlaylistToQueueBody.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddPlaylistToQueueBody.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
});
export type AddPlaylistToQueueBody = z.infer<typeof AddPlaylistToQueueBody>;

// Name: AddToQueue
export const AddToQueue = z.object({
  // Name: AddToQueue.filterId
  "filterId": z.string().optional(),
  // Name: AddToQueue.position
  "position": z.string(),
  // Name: AddToQueue.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddToQueue.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddToQueue.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
});
export type AddToQueue = z.infer<typeof AddToQueue>;

// Name: AddTracksToQueueBody
export const AddTracksToQueueBody = z.object({
  // Name: AddTracksToQueueBody.filterId
  "filterId": z.string().optional(),
  // Name: AddTracksToQueueBody.position
  "position": z.string(),
  // Name: AddTracksToQueueBody.shuffle
  "shuffle": z.boolean().optional(),
  // Name: AddTracksToQueueBody.currentIndex
  "currentIndex": z.number().nullable().optional(),
  // Name: AddTracksToQueueBody.queueIndexToTrackId
  "queueIndexToTrackId": z.string().nullable().optional(),
  // Name: AddTracksToQueueBody.trackIds
  "trackIds": z.array(z.string()),
});
export type AddTracksToQueueBody = z.infer<typeof AddTracksToQueueBody>;

// Name: Images
export const Images = z.object({
  // Name: Images.original
  "original": z.string(),
  // Name: Images.small
  "small": z.string(),
  // Name: Images.medium
  "medium": z.string(),
  // Name: Images.large
  "large": z.string(),
});
export type Images = z.infer<typeof Images>;

// Name: ArtistInfo
export const ArtistInfo = z.object({
  // Name: ArtistInfo.id
  "id": z.string(),
  // Name: ArtistInfo.name
  "name": z.string(),
});
export type ArtistInfo = z.infer<typeof ArtistInfo>;

// Name: Album
export const Album = z.object({
  // Name: Album.id
  "id": z.string(),
  // Name: Album.name
  "name": z.string(),
  // Name: Album.year
  "year": z.number().nullable(),
  // Name: Album.albumType
  "albumType": z.string(),
  // Name: Album.coverArt
  "coverArt": Images,
  // Name: Album.artists
  "artists": z.array(ArtistInfo),
  // Name: Album.tags
  "tags": z.array(z.string()),
  // Name: Album.created
  "created": z.string(),
  // Name: Album.updated
  "updated": z.string(),
});
export type Album = z.infer<typeof Album>;

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
  // Name: ApiToken.created
  "created": z.string(),
  // Name: ApiToken.updated
  "updated": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: Artist
export const Artist = z.object({
  // Name: Artist.id
  "id": z.string(),
  // Name: Artist.name
  "name": z.string(),
  // Name: Artist.coverArt
  "coverArt": Images,
  // Name: Artist.tags
  "tags": z.array(z.string()),
  // Name: Artist.created
  "created": z.string(),
  // Name: Artist.updated
  "updated": z.string(),
});
export type Artist = z.infer<typeof Artist>;

// Name: AuthClaimQuickConnectCodeBody
export const AuthClaimQuickConnectCodeBody = z.object({
  // Name: AuthClaimQuickConnectCodeBody.code
  "code": z.string(),
});
export type AuthClaimQuickConnectCodeBody = z.infer<typeof AuthClaimQuickConnectCodeBody>;

// Name: AuthFinishProvider
export const AuthFinishProvider = z.object({
  // Name: AuthFinishProvider.token
  "token": z.string(),
});
export type AuthFinishProvider = z.infer<typeof AuthFinishProvider>;

// Name: AuthFinishProviderBody
export const AuthFinishProviderBody = z.object({
  // Name: AuthFinishProviderBody.requestId
  "requestId": z.string(),
  // Name: AuthFinishProviderBody.challenge
  "challenge": z.string(),
});
export type AuthFinishProviderBody = z.infer<typeof AuthFinishProviderBody>;

// Name: AuthFinishQuickConnect
export const AuthFinishQuickConnect = z.object({
  // Name: AuthFinishQuickConnect.token
  "token": z.string(),
});
export type AuthFinishQuickConnect = z.infer<typeof AuthFinishQuickConnect>;

// Name: AuthFinishQuickConnectBody
export const AuthFinishQuickConnectBody = z.object({
  // Name: AuthFinishQuickConnectBody.code
  "code": z.string(),
  // Name: AuthFinishQuickConnectBody.challenge
  "challenge": z.string(),
});
export type AuthFinishQuickConnectBody = z.infer<typeof AuthFinishQuickConnectBody>;

// Name: AuthGetProviderStatus
export const AuthGetProviderStatus = z.object({
  // Name: AuthGetProviderStatus.status
  "status": z.string(),
});
export type AuthGetProviderStatus = z.infer<typeof AuthGetProviderStatus>;

// Name: AuthGetProviderStatusBody
export const AuthGetProviderStatusBody = z.object({
  // Name: AuthGetProviderStatusBody.requestId
  "requestId": z.string(),
  // Name: AuthGetProviderStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetProviderStatusBody = z.infer<typeof AuthGetProviderStatusBody>;

// Name: AuthGetQuickConnectStatus
export const AuthGetQuickConnectStatus = z.object({
  // Name: AuthGetQuickConnectStatus.status
  "status": z.string(),
});
export type AuthGetQuickConnectStatus = z.infer<typeof AuthGetQuickConnectStatus>;

// Name: AuthGetQuickConnectStatusBody
export const AuthGetQuickConnectStatusBody = z.object({
  // Name: AuthGetQuickConnectStatusBody.code
  "code": z.string(),
  // Name: AuthGetQuickConnectStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetQuickConnectStatusBody = z.infer<typeof AuthGetQuickConnectStatusBody>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.requestId
  "requestId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.challenge
  "challenge": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthInitiateBody
export const AuthInitiateBody = z.object({
  // Name: AuthInitiateBody.providerId
  "providerId": z.string(),
});
export type AuthInitiateBody = z.infer<typeof AuthInitiateBody>;

// Name: AuthProvider
export const AuthProvider = z.object({
  // Name: AuthProvider.id
  "id": z.string(),
  // Name: AuthProvider.displayName
  "displayName": z.string(),
});
export type AuthProvider = z.infer<typeof AuthProvider>;

// Name: AuthQuickConnectInitiate
export const AuthQuickConnectInitiate = z.object({
  // Name: AuthQuickConnectInitiate.code
  "code": z.string(),
  // Name: AuthQuickConnectInitiate.challenge
  "challenge": z.string(),
  // Name: AuthQuickConnectInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthQuickConnectInitiate = z.infer<typeof AuthQuickConnectInitiate>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: CreatePlaylist
export const CreatePlaylist = z.object({
  // Name: CreatePlaylist.id
  "id": z.string(),
});
export type CreatePlaylist = z.infer<typeof CreatePlaylist>;

// Name: CreatePlaylistBody
export const CreatePlaylistBody = z.object({
  // Name: CreatePlaylistBody.name
  "name": z.string(),
});
export type CreatePlaylistBody = z.infer<typeof CreatePlaylistBody>;

// Name: CreateSSEToken
export const CreateSSEToken = z.object({
  // Name: CreateSSEToken.token
  "token": z.string(),
});
export type CreateSSEToken = z.infer<typeof CreateSSEToken>;

// Name: CreateTrackFilter
export const CreateTrackFilter = z.object({
  // Name: CreateTrackFilter.filterId
  "filterId": z.string(),
});
export type CreateTrackFilter = z.infer<typeof CreateTrackFilter>;

// Name: CreateTrackFilterBody
export const CreateTrackFilterBody = z.object({
  // Name: CreateTrackFilterBody.name
  "name": z.string(),
  // Name: CreateTrackFilterBody.filter
  "filter": z.string(),
});
export type CreateTrackFilterBody = z.infer<typeof CreateTrackFilterBody>;

// Name: EditPlaylistBody
export const EditPlaylistBody = z.object({
  // Name: EditPlaylistBody.name
  "name": z.string().nullable().optional(),
  // Name: EditPlaylistBody.coverUrl
  "coverUrl": z.string().nullable().optional(),
});
export type EditPlaylistBody = z.infer<typeof EditPlaylistBody>;

// Name: GetAlbumById
export const GetAlbumById = z.object({
  // Name: GetAlbumById.album
  "album": Album,
});
export type GetAlbumById = z.infer<typeof GetAlbumById>;

// Name: Track
export const Track = z.object({
  // Name: Track.id
  "id": z.string(),
  // Name: Track.name
  "name": z.string(),
  // Name: Track.order
  "order": z.number().nullable(),
  // Name: Track.duration
  "duration": z.number(),
  // Name: Track.number
  "number": z.number().nullable(),
  // Name: Track.year
  "year": z.number().nullable(),
  // Name: Track.coverArt
  "coverArt": Images,
  // Name: Track.albumId
  "albumId": z.string(),
  // Name: Track.albumName
  "albumName": z.string(),
  // Name: Track.artists
  "artists": z.array(ArtistInfo),
  // Name: Track.tags
  "tags": z.array(z.string()),
  // Name: Track.created
  "created": z.string(),
  // Name: Track.updated
  "updated": z.string(),
});
export type Track = z.infer<typeof Track>;

// Name: GetAlbumTracks
export const GetAlbumTracks = z.object({
  // Name: GetAlbumTracks.tracks
  "tracks": z.array(Track),
});
export type GetAlbumTracks = z.infer<typeof GetAlbumTracks>;

// Name: Page
export const Page = z.object({
  // Name: Page.page
  "page": z.number(),
  // Name: Page.perPage
  "perPage": z.number(),
  // Name: Page.totalItems
  "totalItems": z.number(),
  // Name: Page.totalPages
  "totalPages": z.number(),
});
export type Page = z.infer<typeof Page>;

// Name: GetAlbums
export const GetAlbums = z.object({
  // Name: GetAlbums.page
  "page": Page,
  // Name: GetAlbums.albums
  "albums": z.array(Album),
});
export type GetAlbums = z.infer<typeof GetAlbums>;

// Name: GetApiTokens
export const GetApiTokens = z.object({
  // Name: GetApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetApiTokens = z.infer<typeof GetApiTokens>;

// Name: GetArtistAlbumsById
export const GetArtistAlbumsById = z.object({
  // Name: GetArtistAlbumsById.albums
  "albums": z.array(Album),
});
export type GetArtistAlbumsById = z.infer<typeof GetArtistAlbumsById>;

// Name: GetArtistById
export const GetArtistById = z.object({
  // Name: GetArtistById.artist
  "artist": Artist,
});
export type GetArtistById = z.infer<typeof GetArtistById>;

// Name: GetArtists
export const GetArtists = z.object({
  // Name: GetArtists.page
  "page": Page,
  // Name: GetArtists.artists
  "artists": z.array(Artist),
});
export type GetArtists = z.infer<typeof GetArtists>;

// Name: GetAuthProviders
export const GetAuthProviders = z.object({
  // Name: GetAuthProviders.providers
  "providers": z.array(AuthProvider),
});
export type GetAuthProviders = z.infer<typeof GetAuthProviders>;

// Name: GetFavoriteTrackIds
export const GetFavoriteTrackIds = z.object({
  // Name: GetFavoriteTrackIds.ids
  "ids": z.array(z.string()),
});
export type GetFavoriteTrackIds = z.infer<typeof GetFavoriteTrackIds>;

// Name: TrackHistory
export const TrackHistory = z.object({
  // Name: TrackHistory.id
  "id": z.string(),
  // Name: TrackHistory.userId
  "userId": z.string(),
  // Name: TrackHistory.track
  "track": Track,
  // Name: TrackHistory.listenedAt
  "listenedAt": z.number(),
  // Name: TrackHistory.playbackType
  "playbackType": z.string(),
  // Name: TrackHistory.status
  "status": z.string(),
  // Name: TrackHistory.percentPlayed
  "percentPlayed": z.number(),
  // Name: TrackHistory.created
  "created": z.string(),
  // Name: TrackHistory.updated
  "updated": z.string(),
});
export type TrackHistory = z.infer<typeof TrackHistory>;

// Name: GetHistoryById
export const GetHistoryById = z.object({
  // Name: GetHistoryById.history
  "history": TrackHistory,
});
export type GetHistoryById = z.infer<typeof GetHistoryById>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.email
  "email": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.picture
  "picture": Images,
  // Name: GetMe.quickPlaylist
  "quickPlaylist": z.string().nullable(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: MediaFormat
export const MediaFormat = z.object({
  // Name: MediaFormat.name
  "name": z.string(),
  // Name: MediaFormat.format
  "format": z.string(),
  // Name: MediaFormat.ext
  "ext": z.string(),
  // Name: MediaFormat.qualityHighBitrate
  "qualityHighBitrate": z.number(),
  // Name: MediaFormat.qualityMediumBitrate
  "qualityMediumBitrate": z.number(),
  // Name: MediaFormat.qualityLowBitrate
  "qualityLowBitrate": z.number(),
  // Name: MediaFormat.order
  "order": z.number(),
});
export type MediaFormat = z.infer<typeof MediaFormat>;

// Name: MediaDeviceSpec
export const MediaDeviceSpec = z.object({
  // Name: MediaDeviceSpec.name
  "name": z.string(),
  // Name: MediaDeviceSpec.preferedFormat
  "preferedFormat": z.string(),
  // Name: MediaDeviceSpec.allowedFormats
  "allowedFormats": z.array(z.string()),
});
export type MediaDeviceSpec = z.infer<typeof MediaDeviceSpec>;

// Name: GetMediaSettings
export const GetMediaSettings = z.object({
  // Name: GetMediaSettings.formats
  "formats": z.array(MediaFormat),
  // Name: GetMediaSettings.deviceSpecs
  "deviceSpecs": z.array(MediaDeviceSpec),
});
export type GetMediaSettings = z.infer<typeof GetMediaSettings>;

// Name: Playlist
export const Playlist = z.object({
  // Name: Playlist.id
  "id": z.string(),
  // Name: Playlist.name
  "name": z.string(),
  // Name: Playlist.coverArt
  "coverArt": Images,
  // Name: Playlist.ownerId
  "ownerId": z.string(),
  // Name: Playlist.ownerDisplayName
  "ownerDisplayName": z.string(),
  // Name: Playlist.ownerPicture
  "ownerPicture": Images,
  // Name: Playlist.trackCount
  "trackCount": z.number(),
  // Name: Playlist.created
  "created": z.string(),
  // Name: Playlist.updated
  "updated": z.string(),
});
export type Playlist = z.infer<typeof Playlist>;

// Name: GetPlaylistById
export const GetPlaylistById = z.object({
  // Name: GetPlaylistById.playlist
  "playlist": Playlist,
});
export type GetPlaylistById = z.infer<typeof GetPlaylistById>;

// Name: GetPlaylistItemIds
export const GetPlaylistItemIds = z.object({
  // Name: GetPlaylistItemIds.ids
  "ids": z.array(z.string()),
});
export type GetPlaylistItemIds = z.infer<typeof GetPlaylistItemIds>;

// Name: GetPlaylistItems
export const GetPlaylistItems = z.object({
  // Name: GetPlaylistItems.page
  "page": Page,
  // Name: GetPlaylistItems.items
  "items": z.array(Track),
});
export type GetPlaylistItems = z.infer<typeof GetPlaylistItems>;

// Name: GetPlaylists
export const GetPlaylists = z.object({
  // Name: GetPlaylists.page
  "page": Page,
  // Name: GetPlaylists.playlists
  "playlists": z.array(Playlist),
});
export type GetPlaylists = z.infer<typeof GetPlaylists>;

// Name: QueueItem
export const QueueItem = z.object({
  // Name: QueueItem.queueItemId
  "queueItemId": z.string(),
  // Name: QueueItem.track
  "track": Track,
});
export type QueueItem = z.infer<typeof QueueItem>;

// Name: GetQueue
export const GetQueue = z.object({
  // Name: GetQueue.currentIndex
  "currentIndex": z.number(),
  // Name: GetQueue.items
  "items": z.array(QueueItem),
  // Name: GetQueue.page
  "page": Page,
});
export type GetQueue = z.infer<typeof GetQueue>;

// Name: QueueIdItem
export const QueueIdItem = z.object({
  // Name: QueueIdItem.queueItemId
  "queueItemId": z.string(),
  // Name: QueueIdItem.trackId
  "trackId": z.string(),
});
export type QueueIdItem = z.infer<typeof QueueIdItem>;

// Name: GetQueueIds
export const GetQueueIds = z.object({
  // Name: GetQueueIds.currentIndex
  "currentIndex": z.number(),
  // Name: GetQueueIds.items
  "items": z.array(QueueIdItem),
});
export type GetQueueIds = z.infer<typeof GetQueueIds>;

// Name: GetQueueItem
export const GetQueueItem = z.object({
  // Name: GetQueueItem.item
  "item": QueueItem,
});
export type GetQueueItem = z.infer<typeof GetQueueItem>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: Tag
export const Tag = z.object({
  // Name: Tag.slug
  "slug": z.string(),
});
export type Tag = z.infer<typeof Tag>;

// Name: GetTags
export const GetTags = z.object({
  // Name: GetTags.tags
  "tags": z.array(Tag),
});
export type GetTags = z.infer<typeof GetTags>;

// Name: GetTrackById
export const GetTrackById = z.object({
  // Name: GetTrackById.track
  "track": Track,
});
export type GetTrackById = z.infer<typeof GetTrackById>;

// Name: TrackFilter
export const TrackFilter = z.object({
  // Name: TrackFilter.filterId
  "filterId": z.string(),
  // Name: TrackFilter.userId
  "userId": z.string(),
  // Name: TrackFilter.name
  "name": z.string(),
  // Name: TrackFilter.filter
  "filter": z.string(),
  // Name: TrackFilter.created
  "created": z.string(),
  // Name: TrackFilter.updated
  "updated": z.string(),
});
export type TrackFilter = z.infer<typeof TrackFilter>;

// Name: GetTrackFilters
export const GetTrackFilters = z.object({
  // Name: GetTrackFilters.filters
  "filters": z.array(TrackFilter),
});
export type GetTrackFilters = z.infer<typeof GetTrackFilters>;

// Name: GetTrackHistory
export const GetTrackHistory = z.object({
  // Name: GetTrackHistory.page
  "page": Page,
  // Name: GetTrackHistory.history
  "history": z.array(TrackHistory),
});
export type GetTrackHistory = z.infer<typeof GetTrackHistory>;

// Name: GetTracks
export const GetTracks = z.object({
  // Name: GetTracks.page
  "page": Page,
  // Name: GetTracks.tracks
  "tracks": z.array(Track),
});
export type GetTracks = z.infer<typeof GetTracks>;

// Name: UserData
export const UserData = z.object({
  // Name: UserData.id
  "id": z.string(),
  // Name: UserData.displayName
  "displayName": z.string(),
  // Name: UserData.role
  "role": z.string(),
  // Name: UserData.picture
  "picture": Images,
  // Name: UserData.created
  "created": z.string(),
});
export type UserData = z.infer<typeof UserData>;

// Name: GetUser
export const GetUser = z.object({
  // Name: GetUser.user
  "user": UserData,
});
export type GetUser = z.infer<typeof GetUser>;

// Name: GetUserFavorites
export const GetUserFavorites = z.object({
  // Name: GetUserFavorites.page
  "page": Page,
  // Name: GetUserFavorites.items
  "items": z.array(Track),
});
export type GetUserFavorites = z.infer<typeof GetUserFavorites>;

// Name: GetUserStats
export const GetUserStats = z.object({
  // Name: GetUserStats.numTracksPlayed
  "numTracksPlayed": z.number(),
  // Name: GetUserStats.numTracksSkipped
  "numTracksSkipped": z.number(),
  // Name: GetUserStats.numPlaylistsCreated
  "numPlaylistsCreated": z.number(),
  // Name: GetUserStats.numFavoriteTracks
  "numFavoriteTracks": z.number(),
  // Name: GetUserStats.listeningTime
  "listeningTime": z.number(),
  // Name: GetUserStats.lastListenedAt
  "lastListenedAt": z.number().nullable(),
  // Name: GetUserStats.updated
  "updated": z.string(),
});
export type GetUserStats = z.infer<typeof GetUserStats>;

// Name: GetUserTopTracks
export const GetUserTopTracks = z.object({
  // Name: GetUserTopTracks.tracks
  "tracks": z.array(Track),
});
export type GetUserTopTracks = z.infer<typeof GetUserTopTracks>;

// Name: YearStat
export const YearStat = z.object({
  // Name: YearStat.year
  "year": z.number(),
  // Name: YearStat.trackCount
  "trackCount": z.number(),
  // Name: YearStat.listeningTime
  "listeningTime": z.number(),
});
export type YearStat = z.infer<typeof YearStat>;

// Name: GetUserYearStats
export const GetUserYearStats = z.object({
  // Name: GetUserYearStats.stats
  "stats": z.array(YearStat),
});
export type GetUserYearStats = z.infer<typeof GetUserYearStats>;

// Name: PushTrackHistory
export const PushTrackHistory = z.object({
  // Name: PushTrackHistory.id
  "id": z.string(),
});
export type PushTrackHistory = z.infer<typeof PushTrackHistory>;

// Name: PushTrackHistoryBody
export const PushTrackHistoryBody = z.object({
  // Name: PushTrackHistoryBody.trackId
  "trackId": z.string(),
  // Name: PushTrackHistoryBody.playbackType
  "playbackType": z.string(),
  // Name: PushTrackHistoryBody.percentPlayed
  "percentPlayed": z.number(),
});
export type PushTrackHistoryBody = z.infer<typeof PushTrackHistoryBody>;

// Name: RemovePlaylistItemBody
export const RemovePlaylistItemBody = z.object({
  // Name: RemovePlaylistItemBody.trackId
  "trackId": z.string(),
});
export type RemovePlaylistItemBody = z.infer<typeof RemovePlaylistItemBody>;

// Name: ReorderPlaylistItemsBody
export const ReorderPlaylistItemsBody = z.object({
  // Name: ReorderPlaylistItemsBody.before
  "before": z.boolean(),
  // Name: ReorderPlaylistItemsBody.anchorTrackId
  "anchorTrackId": z.string(),
  // Name: ReorderPlaylistItemsBody.trackIds
  "trackIds": z.array(z.string()),
});
export type ReorderPlaylistItemsBody = z.infer<typeof ReorderPlaylistItemsBody>;

// Name: SearchAlbums
export const SearchAlbums = z.object({
  // Name: SearchAlbums.page
  "page": Page,
  // Name: SearchAlbums.albums
  "albums": z.array(Album),
});
export type SearchAlbums = z.infer<typeof SearchAlbums>;

// Name: SearchArtists
export const SearchArtists = z.object({
  // Name: SearchArtists.page
  "page": Page,
  // Name: SearchArtists.artists
  "artists": z.array(Artist),
});
export type SearchArtists = z.infer<typeof SearchArtists>;

// Name: SearchPlaylists
export const SearchPlaylists = z.object({
  // Name: SearchPlaylists.page
  "page": Page,
  // Name: SearchPlaylists.playlists
  "playlists": z.array(Playlist),
});
export type SearchPlaylists = z.infer<typeof SearchPlaylists>;

// Name: SearchTracks
export const SearchTracks = z.object({
  // Name: SearchTracks.page
  "page": Page,
  // Name: SearchTracks.tracks
  "tracks": z.array(Track),
});
export type SearchTracks = z.infer<typeof SearchTracks>;

// Name: SearchUsers
export const SearchUsers = z.object({
  // Name: SearchUsers.page
  "page": Page,
  // Name: SearchUsers.users
  "users": z.array(UserData),
});
export type SearchUsers = z.infer<typeof SearchUsers>;

// Name: SetQueuePositionBody
export const SetQueuePositionBody = z.object({
  // Name: SetQueuePositionBody.index
  "index": z.number(),
});
export type SetQueuePositionBody = z.infer<typeof SetQueuePositionBody>;

// Name: SetQuickPlaylistBody
export const SetQuickPlaylistBody = z.object({
  // Name: SetQuickPlaylistBody.playlistId
  "playlistId": z.string(),
});
export type SetQuickPlaylistBody = z.infer<typeof SetQuickPlaylistBody>;

// Name: UpdateMeBody
export const UpdateMeBody = z.object({
  // Name: UpdateMeBody.displayName
  "displayName": z.string().nullable().optional(),
  // Name: UpdateMeBody.pictureUrl
  "pictureUrl": z.string().nullable().optional(),
});
export type UpdateMeBody = z.infer<typeof UpdateMeBody>;

// Name: UpdateTrackFilterBody
export const UpdateTrackFilterBody = z.object({
  // Name: UpdateTrackFilterBody.name
  "name": z.string().nullable().optional(),
  // Name: UpdateTrackFilterBody.filter
  "filter": z.string().nullable().optional(),
});
export type UpdateTrackFilterBody = z.infer<typeof UpdateTrackFilterBody>;

