// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api


func (c *Client) AddItemToPlaylist(playlistId string, body AddItemToPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AddTrackEvent(trackId string, body AddTrackEventBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/media/event/track/%v", trackId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AddUserFavorite(trackId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/favorites/%v", trackId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}


func (c *Client) AuthClaimQuickConnectCode(body AuthClaimQuickConnectCodeBody, options Options) (*any, error) {
	path := "/api/v1/auth/quick-connect/claim"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AuthFinishProvider(body AuthFinishProviderBody, options Options) (*AuthFinishProvider, error) {
	path := "/api/v1/auth/providers/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishProvider](data, body)
}

func (c *Client) AuthFinishQuickConnect(body AuthFinishQuickConnectBody, options Options) (*AuthFinishQuickConnect, error) {
	path := "/api/v1/auth/quick-connect/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishQuickConnect](data, body)
}

func (c *Client) AuthGetProviderStatus(body AuthGetProviderStatusBody, options Options) (*AuthGetProviderStatus, error) {
	path := "/api/v1/auth/provider/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetProviderStatus](data, body)
}

func (c *Client) AuthGetProviders(options Options) (*GetAuthProviders, error) {
	path := "/api/v1/auth/providers"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAuthProviders](data, nil)
}

func (c *Client) AuthGetQuickConnectStatus(body AuthGetQuickConnectStatusBody, options Options) (*AuthGetQuickConnectStatus, error) {
	path := "/api/v1/auth/quick-connect/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetQuickConnectStatus](data, body)
}

func (c *Client) AuthProviderInitiate(body AuthInitiateBody, options Options) (*AuthInitiate, error) {
	path := "/api/v1/auth/providers/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthInitiate](data, body)
}

func (c *Client) AuthQuickConnectInitiate(options Options) (*AuthQuickConnectInitiate, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthQuickConnectInitiate](data, nil)
}

func (c *Client) CreateApiToken(body CreateApiTokenBody, options Options) (*CreateApiToken, error) {
	path := "/api/v1/user/apitoken"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateApiToken](data, body)
}

func (c *Client) CreatePlaylist(body CreatePlaylistBody, options Options) (*CreatePlaylist, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreatePlaylist](data, body)
}

func (c *Client) CreatePlaylistFilter(playlistId string, body AddPlaylistFilterBody, options Options) (*AddPlaylistFilter, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AddPlaylistFilter](data, body)
}

func (c *Client) CreateTrackFilter(body CreateTrackFilterBody, options Options) (*CreateTrackFilter, error) {
	path := "/api/v1/user/tracks/filter"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateTrackFilter](data, body)
}

func (c *Client) DeleteApiToken(id string, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/apitoken/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeletePlaylist(playlistId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeleteTrackFilter(filterId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/tracks/filter/%v", filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) EditPlaylist(playlistId string, body EditPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) EditPlaylistFilter(playlistId string, filterId string, body EditPlaylistFilterBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/filters/%v", playlistId, filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) EditTrackFilter(filterId string, body EditTrackFilterBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/tracks/filter/%v", filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) EditUser(body EditUserBody, options Options) (*any, error) {
	path := "/api/v1/user"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) GeneratePlaylistImage(playlistId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) GetAlbumById(id string, options Options) (*GetAlbumById, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumById](data, nil)
}


func (c *Client) GetAlbumTracks(id string, options Options) (*GetAlbumTracks, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumTracks](data, nil)
}

func (c *Client) GetAlbums(options Options) (*GetAlbums, error) {
	path := "/api/v1/albums"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbums](data, nil)
}

func (c *Client) GetAllApiTokens(options Options) (*GetAllApiTokens, error) {
	path := "/api/v1/user/apitoken"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAllApiTokens](data, nil)
}

func (c *Client) GetArtistAlbums(id string, options Options) (*GetArtistAlbumsById, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistAlbumsById](data, nil)
}

func (c *Client) GetArtistById(id string, options Options) (*GetArtistById, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistById](data, nil)
}


func (c *Client) GetArtists(options Options) (*GetArtists, error) {
	path := "/api/v1/artists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtists](data, nil)
}

func (c *Client) GetMe(options Options) (*GetMe, error) {
	path := "/api/v1/auth/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMe](data, nil)
}

func (c *Client) GetMediaFromAlbum(albumId string, body GetMediaFromAlbumBody, options Options) (*GetMedia, error) {
	path := Sprintf("/api/v1/media/album/%v", albumId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromArtist(artistId string, body GetMediaFromArtistBody, options Options) (*GetMedia, error) {
	path := Sprintf("/api/v1/media/artist/%v", artistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromFilter(body GetMediaFromFilterBody, options Options) (*GetMedia, error) {
	path := "/api/v1/media/filter"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaFromIds(body GetMediaFromIdsBody, options Options) (*GetMedia, error) {
	path := "/api/v1/media/ids"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMedia](data, body)
}

func (c *Client) GetMediaSettings(options Options) (*GetMediaSettings, error) {
	path := "/api/v1/media/settings"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMediaSettings](data, nil)
}

func (c *Client) GetPlaylistById(playlistId string, options Options) (*GetPlaylistById, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistById](data, nil)
}

func (c *Client) GetPlaylistFilters(playlistId string, options Options) (*GetPlaylistFilters, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistFilters](data, nil)
}


func (c *Client) GetPlaylistItems(playlistId string, options Options) (*GetPlaylistItems, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistItems](data, nil)
}

func (c *Client) GetPlaylists(options Options) (*GetPlaylists, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylists](data, nil)
}

func (c *Client) GetSystemInfo(options Options) (*GetSystemInfo, error) {
	path := "/api/v1/system/info"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetSystemInfo](data, nil)
}

func (c *Client) GetTrackById(id string, options Options) (*GetTrackById, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTrackById](data, nil)
}

func (c *Client) GetTrackFilters(userId string, options Options) (*GetTrackFilters, error) {
	path := Sprintf("/api/v1/user/%v/tracks/filter", userId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTrackFilters](data, nil)
}

func (c *Client) GetTracks(options Options) (*GetTracks, error) {
	path := "/api/v1/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTracks](data, nil)
}

func (c *Client) GetUser(id string, options Options) (*GetUser, error) {
	path := Sprintf("/api/v1/users/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUser](data, nil)
}

func (c *Client) GetUserFavorites(options Options) (*GetUserFavorites, error) {
	path := "/api/v1/user/favorites"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUserFavorites](data, nil)
}

func (c *Client) GetUserFavoritesIds(options Options) (*GetUserFavoritesIds, error) {
	path := "/api/v1/user/favorites/ids"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUserFavoritesIds](data, nil)
}


func (c *Client) GetUserQuickPlaylistItemIds(options Options) (*GetUserQuickPlaylistItemIds, error) {
	path := "/api/v1/user/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUserQuickPlaylistItemIds](data, nil)
}

func (c *Client) RemovePlaylistItem(playlistId string, body RemovePlaylistItemBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) RemoveUserFavorite(trackId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/user/favorites/%v", trackId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) ReorderPlaylistItems(playlistId string, body ReorderPlaylistItemsBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items/reorder", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) RunJob(jobName string, options Options) (*any, error) {
	path := Sprintf("/api/v1/system/job/%v", jobName)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) SearchAlbums(options Options) (*SearchAlbums, error) {
	path := "/api/v1/search/albums"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchAlbums](data, nil)
}

func (c *Client) SearchArtists(options Options) (*SearchArtists, error) {
	path := "/api/v1/search/artists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchArtists](data, nil)
}

func (c *Client) SearchPlaylists(options Options) (*SearchPlaylists, error) {
	path := "/api/v1/search/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchPlaylists](data, nil)
}

func (c *Client) SearchTracks(options Options) (*SearchTracks, error) {
	path := "/api/v1/search/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchTracks](data, nil)
}

func (c *Client) SearchUsers(options Options) (*SearchUsers, error) {
	path := "/api/v1/search/users"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchUsers](data, nil)
}



func (c *Client) UpdateUserSettings(body UpdateUserSettingsBody, options Options) (*any, error) {
	path := "/api/v1/user/settings"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) UploadPlaylistImage(playlistId string, boundary string, body Reader, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/image/upload", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return RequestForm[any](data, boundary, body)
}

func (c *ClientUrls) AddItemToPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) AddTrackEvent(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/media/event/track/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) AddUserFavorite(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/user/favorites/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) AuthCallback() (*URL, error) {
	path := "/api/v1/auth/providers/callback"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthClaimQuickConnectCode() (*URL, error) {
	path := "/api/v1/auth/quick-connect/claim"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishProvider() (*URL, error) {
	path := "/api/v1/auth/providers/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishQuickConnect() (*URL, error) {
	path := "/api/v1/auth/quick-connect/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviderStatus() (*URL, error) {
	path := "/api/v1/auth/provider/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviders() (*URL, error) {
	path := "/api/v1/auth/providers"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetQuickConnectStatus() (*URL, error) {
	path := "/api/v1/auth/quick-connect/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthProviderInitiate() (*URL, error) {
	path := "/api/v1/auth/providers/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthQuickConnectInitiate() (*URL, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) CreateApiToken() (*URL, error) {
	path := "/api/v1/user/apitoken"
	return c.getUrl(path)
}

func (c *ClientUrls) CreatePlaylist() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) CreatePlaylistFilter(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) CreateTrackFilter() (*URL, error) {
	path := "/api/v1/user/tracks/filter"
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteApiToken(id string) (*URL, error) {
	path := Sprintf("/api/v1/user/apitoken/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) DeletePlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteTrackFilter(filterId string) (*URL, error) {
	path := Sprintf("/api/v1/user/tracks/filter/%v", filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) EditPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) EditPlaylistFilter(playlistId string, filterId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters/%v", playlistId, filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) EditTrackFilter(filterId string) (*URL, error) {
	path := Sprintf("/api/v1/user/tracks/filter/%v", filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) EditUser() (*URL, error) {
	path := "/api/v1/user"
	return c.getUrl(path)
}

func (c *ClientUrls) GeneratePlaylistImage(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumById(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumImage(albumId string, image string) (*URL, error) {
	path := Sprintf("/files/albums/images/%v/%v", albumId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumTracks(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbums() (*URL, error) {
	path := "/api/v1/albums"
	return c.getUrl(path)
}

func (c *ClientUrls) GetAllApiTokens() (*URL, error) {
	path := "/api/v1/user/apitoken"
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistAlbums(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistById(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistImage(artistId string, image string) (*URL, error) {
	path := Sprintf("/files/artists/images/%v/%v", artistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtists() (*URL, error) {
	path := "/api/v1/artists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMe() (*URL, error) {
	path := "/api/v1/auth/me"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromAlbum(albumId string) (*URL, error) {
	path := Sprintf("/api/v1/media/album/%v", albumId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromArtist(artistId string) (*URL, error) {
	path := Sprintf("/api/v1/media/artist/%v", artistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromFilter() (*URL, error) {
	path := "/api/v1/media/filter"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaFromIds() (*URL, error) {
	path := "/api/v1/media/ids"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaSettings() (*URL, error) {
	path := "/api/v1/media/settings"
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistById(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistFilters(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/filters", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistImage(playlistId string, image string) (*URL, error) {
	path := Sprintf("/files/playlists/images/%v/%v", playlistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistItems(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylists() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetSystemInfo() (*URL, error) {
	path := "/api/v1/system/info"
	return c.getUrl(path)
}

func (c *ClientUrls) GetTrackById(id string) (*URL, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetTrackFilters(userId string) (*URL, error) {
	path := Sprintf("/api/v1/user/%v/tracks/filter", userId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetTracks() (*URL, error) {
	path := "/api/v1/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUser(id string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserFavorites() (*URL, error) {
	path := "/api/v1/user/favorites"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserFavoritesIds() (*URL, error) {
	path := "/api/v1/user/favorites/ids"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserImage(userId string, image string) (*URL, error) {
	path := Sprintf("/files/users/images/%v/%v", userId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserQuickPlaylistItemIds() (*URL, error) {
	path := "/api/v1/user/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) RemovePlaylistItem(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) RemoveUserFavorite(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/user/favorites/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) ReorderPlaylistItems(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items/reorder", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) RunJob(jobName string) (*URL, error) {
	path := Sprintf("/api/v1/system/job/%v", jobName)
	return c.getUrl(path)
}

func (c *ClientUrls) SearchAlbums() (*URL, error) {
	path := "/api/v1/search/albums"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchArtists() (*URL, error) {
	path := "/api/v1/search/artists"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchPlaylists() (*URL, error) {
	path := "/api/v1/search/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchTracks() (*URL, error) {
	path := "/api/v1/search/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchUsers() (*URL, error) {
	path := "/api/v1/search/users"
	return c.getUrl(path)
}

func (c *ClientUrls) SseHandler() (*URL, error) {
	path := "/api/v1/system/sse"
	return c.getUrl(path)
}

func (c *ClientUrls) StreamTrack(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/media/stream/tracks/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateUserSettings() (*URL, error) {
	path := "/api/v1/user/settings"
	return c.getUrl(path)
}

func (c *ClientUrls) UploadPlaylistImage(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/image/upload", playlistId)
	return c.getUrl(path)
}
